var mediadata = [
{ mediatitle: "Άλφα Radio 96", city: "ΣΕΡΡΕΣ", mediaid: 1197, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "1055 Rock 105,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 116, logo: "/logos/gr/mini/rock1055.gif" }, 
{ mediatitle: "1431 AM 1431", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 52, logo: "/logos/gr/mini/1431.gif" }, 
{ mediatitle: "80smania ", city: "INTERNET RADIO", mediaid: 1883, logo: "/logos/gr/mini/80smania.gif" }, 
{ mediatitle: "88 μισό 88,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 137, logo: "/logos/gr/mini/88miso.gif" }, 
{ mediatitle: "926FM (ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ) 92,6", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 787, logo: "/logos/gr/mini/tichero.gif" }, 
{ mediatitle: "99,6 Radio ", city: "ΧΑΝΙΑ", mediaid: 692, logo: "/logos/gr/mini/radio996.gif" }, 
{ mediatitle: "99fm / Radio 1 ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 532, logo: "/logos/gr/mini/99fm.gif" }, 
{ mediatitle: "A100 107,4", city: "ΑΘΗΝΑ", mediaid: 392, logo: "/logos/gr/mini/a100.gif" }, 
{ mediatitle: "Act Radio ", city: "INTERNET RADIO", mediaid: 1884, logo: "/logos/gr/mini/actradiogr.gif" }, 
{ mediatitle: "Action Radio Κόνιτσα 98,2", city: "ΚΟΝΙΤΣΑ", mediaid: 871, logo: "/logos/gr/mini/actionradio.gif" }, 
{ mediatitle: "Active Radio ", city: "INTERNET RADIO", mediaid: 48, logo: "/logos/gr/mini/activeradio.gif" }, 
{ mediatitle: "Akous. Breeze ", city: "ΑΘΗΝΑ", mediaid: 1709, logo: "/logos/gr/mini/akous_breeze.gif" }, 
{ mediatitle: "Akous. Edgar's Stage ", city: "ΑΘΗΝΑ", mediaid: 1707, logo: "/logos/gr/mini/akousstage_edgar.gif" }, 
{ mediatitle: "Akous. Gazi ", city: "ΑΘΗΝΑ", mediaid: 1706, logo: "/logos/gr/mini/akous_gazi.gif" }, 
{ mediatitle: "Akous. InLove ", city: "ΑΘΗΝΑ", mediaid: 1839, logo: "/logos/gr/mini/akous_inlove.gif" }, 
{ mediatitle: "Akous. JazzIN ", city: "INTERNET RADIO", mediaid: 1870, logo: "/logos/gr/mini/akous_jazzin.gif" }, 
{ mediatitle: "Akous. MusicES ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 6, logo: "/logos/gr/mini/akous_musices.gif" }, 
{ mediatitle: "Akous. My Classic ", city: "INTERNET RADIO", mediaid: 1869, logo: "/logos/gr/mini/akous_myclassic.gif" }, 
{ mediatitle: "Akous.Domotel Deluxe ", city: "ΑΘΗΝΑ", mediaid: 1708, logo: "/logos/gr/mini/akous_domoteldeluxe.gif" }, 
{ mediatitle: "Aktina Radio 104,7", city: "ΚΕΡΚΥΡΑ", mediaid: 840, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Alina Radio ", city: "INTERNET RADIO", mediaid: 1853, logo: "/logos/gr/mini/alina.gif" }, 
{ mediatitle: "AllDay DJ ", city: "INTERNET RADIO", mediaid: 1917, logo: "/logos/gr/mini/alldaydj.gif" }, 
{ mediatitle: "Alpha 98,1", city: "ΠΡΕΒΕΖΑ", mediaid: 952, logo: "/logos/gr/mini/alpha981.gif" }, 
{ mediatitle: "Amore Fm 107,9", city: "ΡΕΘΥΜΝΟ", mediaid: 649, logo: "/logos/gr/mini/amorefm.gif" }, 
{ mediatitle: "Ant1 Radio 97,2", city: "ΑΘΗΝΑ", mediaid: 214, logo: "/logos/gr/mini/ant1radio.gif" }, 
{ mediatitle: "Ant1 Αιγαίο 105", city: "ΧΙΟΣ", mediaid: 499, logo: "/logos/gr/mini/aegeanant1.gif" }, 
{ mediatitle: "Ant1 Θεσσαλονίκης 97,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 531, logo: "/logos/gr/mini/ant1thess.gif" }, 
{ mediatitle: "Antenna Κέρκυρα 92,6", city: "ΚΕΡΚΥΡΑ", mediaid: 216, logo: "/logos/gr/mini/ant1kerkyra.gif" }, 
{ mediatitle: "Antenna Ν.Ελλάδας 97,1", city: "ΣΠΑΡΤΗ", mediaid: 710, logo: "/logos/gr/mini/ant1south.gif" }, 
{ mediatitle: "Aquarius Fm 105,5", city: "ΠΥΡΓΟΣ", mediaid: 660, logo: "/logos/gr/mini/aquarius.gif" }, 
{ mediatitle: "Arion 2 ", city: "ΑΘΗΝΑ", mediaid: 5, logo: "/logos/gr/mini/arion_2.gif" }, 
{ mediatitle: "Arion Kids ", city: "ΑΘΗΝΑ", mediaid: 8, logo: "/logos/gr/mini/arionkids.gif" }, 
{ mediatitle: "Arion Radio ", city: "ΑΘΗΝΑ", mediaid: 1, logo: "/logos/gr/mini/arionradio.gif" }, 
{ mediatitle: "Arion Λαϊκός ", city: "ΑΘΗΝΑ", mediaid: 7, logo: "/logos/gr/mini/arionlaikos.gif" }, 
{ mediatitle: "Astra 97,3", city: "ΒΟΛΟΣ", mediaid: 117, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Astra Radio ", city: "ΜΥΤΙΛΗΝΗ", mediaid: 897, logo: "/logos/gr/mini/astraradio.gif" }, 
{ mediatitle: "Astro Fm 99,8", city: "ΑΘΗΝΑ", mediaid: 890, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Astro Fm 96,4", city: "ΡΕΘΥΜΝΟ", mediaid: 205, logo: "/logos/gr/mini/radioastro.gif" }, 
{ mediatitle: "Astros Radio ", city: "INTERNET RADIO", mediaid: 697, logo: "/logos/gr/mini/astrosradio.gif" }, 
{ mediatitle: "Athens 111 FM ", city: "INTERNET RADIO", mediaid: 1822, logo: "/logos/gr/mini/athens111.gif" }, 
{ mediatitle: "Athens DeeJay 95,2", city: "ΑΘΗΝΑ", mediaid: 420, logo: "/logos/gr/mini/deejay.gif" }, 
{ mediatitle: "Athens FM ", city: "ΑΘΗΝΑ", mediaid: 1820, logo: "/logos/gr/mini/athensfm.gif" }, 
{ mediatitle: "Athens Party ", city: "ΑΘΗΝΑ", mediaid: 2, logo: "/logos/gr/mini/athensparty.gif" }, 
{ mediatitle: "Athens Winder Radio ", city: "INTERNET RADIO", mediaid: 1786, logo: "/logos/gr/mini/athenswinder.gif" }, 
{ mediatitle: "Athletic 104,2", city: "ΗΡΑΚΛΕΙΟ", mediaid: 206, logo: "/logos/gr/mini/athletic.gif" }, 
{ mediatitle: "Atlantis 105,2", city: "ΑΘΗΝΑ", mediaid: 395, logo: "/logos/gr/mini/atlantis.gif" }, 
{ mediatitle: "Avanti Fm 98,3", city: "ΣΚΙΑΘΟΣ", mediaid: 634, logo: "/logos/gr/mini/avantiradio.gif" }, 
{ mediatitle: "Avanti FM 97,7", city: "ΛΑΜΙΑ", mediaid: 1759, logo: "/logos/gr/mini/avantifm977.gif" }, 
{ mediatitle: "Avanti Fm 107,6", city: "ΛΑΡΙΣΑ", mediaid: 718, logo: "/logos/gr/mini/avantifm.gif" }, 
{ mediatitle: "Aλήθεια 95,7", city: "ΧΙΟΣ", mediaid: 316, logo: "/logos/gr/mini/alitheia.gif" }, 
{ mediatitle: "B.F.M. iRadio ", city: "ΕΔΕΣΣΑ", mediaid: 1960, logo: "/logos/gr/mini/bfmiradio.gif" }, 
{ mediatitle: "Balloni ", city: "INTERNET RADIO", mediaid: 846, logo: "/logos/gr/mini/balloni.gif" }, 
{ mediatitle: "Beatmixx ", city: "INTERNET RADIO", mediaid: 1940, logo: "/logos/gr/mini/beatmixx.gif" }, 
{ mediatitle: "Best 94,7", city: "ΗΡΑΚΛΕΙΟ", mediaid: 808, logo: "/logos/gr/mini/best947.gif" }, 
{ mediatitle: "Best  103,3", city: "ΠΥΡΓΟΣ", mediaid: 695, logo: "/logos/gr/mini/best1033.gif" }, 
{ mediatitle: "Best 92,6", city: "ΑΘΗΝΑ", mediaid: 95, logo: "/logos/gr/mini/bestradio.gif" }, 
{ mediatitle: "Best Fm 98,1", city: "ΜΥΤΙΛΗΝΗ", mediaid: 472, logo: "/logos/gr/mini/bestmytilini.gif" }, 
{ mediatitle: "Best Fm 93,3", city: "ΛΑΡΙΣΑ", mediaid: 725, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Best Radio 97,3", city: "ΚΑΛΑΜΑΤΑ", mediaid: 377, logo: "/logos/gr/mini/bestradio973.gif" }, 
{ mediatitle: "Best Radio 101,1", city: "ΚΩΣ", mediaid: 180, logo: "/logos/gr/mini/bestkos.gif" }, 
{ mediatitle: "Biscuit Radio  ", city: "INTERNET RADIO", mediaid: 1939, logo: "/logos/gr/mini/biscuitgr.gif" }, 
{ mediatitle: "Black Lemon Radio ", city: "INTERNET RADIO", mediaid: 946, logo: "/logos/gr/mini/blacklemon.gif" }, 
{ mediatitle: "BlackMan ", city: "INTERNET RADIO", mediaid: 836, logo: "/logos/gr/mini/blackman.gif" }, 
{ mediatitle: "Bleep Radio ", city: "INTERNET RADIO", mediaid: 1840, logo: "/logos/gr/mini/bleep.gif" }, 
{ mediatitle: "Blue Radio ", city: "INTERNET RADIO", mediaid: 794, logo: "/logos/gr/mini/blueradio.gif" }, 
{ mediatitle: "Bravo 89,6", city: "ΖΑΚΥΝΘΟΣ", mediaid: 737, logo: "/logos/gr/mini/bravo.gif" }, 
{ mediatitle: "BUZZ Radio ", city: "INTERNET RADIO", mediaid: 1862, logo: "/logos/gr/mini/buzz.gif" }, 
{ mediatitle: "Camelot 100,8", city: "ΚΥΘΗΡΑ", mediaid: 1810, logo: "/logos/gr/mini/camelot.gif" }, 
{ mediatitle: "Capital 97,7", city: "ΚΑΤΕΡΙΝΗ", mediaid: 68, logo: "/logos/gr/mini/capital977.gif" }, 
{ mediatitle: "Capital Radio 90,7", city: "ΡΕΘΥΜΝΟ", mediaid: 417, logo: "/logos/gr/mini/capitalradio.gif" }, 
{ mediatitle: "City 93", city: "ΚΩΣ", mediaid: 631, logo: "/logos/gr/mini/city93.gif" }, 
{ mediatitle: "City Fm 100", city: "ΗΡΑΚΛΕΙΟ", mediaid: 530, logo: "/logos/gr/mini/cityfm.gif" }, 
{ mediatitle: "City Fm 103,8", city: "ΚΑΛΑΜΑΤΑ", mediaid: 655, logo: "/logos/gr/mini/cityfm1038.gif" }, 
{ mediatitle: "Classical Radio ", city: "INTERNET RADIO", mediaid: 1780, logo: "/logos/gr/mini/classicalradio.gif" }, 
{ mediatitle: "Club Denso ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1833, logo: "/logos/gr/mini/clubdenso.gif" }, 
{ mediatitle: "Club FM 93,7", city: "ΙΕΡΑΠΕΤΡΑ", mediaid: 409, logo: "/logos/gr/mini/clubfm.gif" }, 
{ mediatitle: "Club's Radio ", city: "INTERNET RADIO", mediaid: 1858, logo: "/logos/gr/mini/clubsradio.gif" }, 
{ mediatitle: "Cookie Rock ", city: "INTERNET RADIO", mediaid: 1788, logo: "/logos/gr/mini/cookierock.gif" }, 
{ mediatitle: "Cool Fm 90,7", city: "ΑΡΓΟΣ", mediaid: 289, logo: "/logos/gr/mini/cool907.gif" }, 
{ mediatitle: "Cool Radio ", city: "INTERNET RADIO", mediaid: 790, logo: "/logos/gr/mini/coolfmeu.gif" }, 
{ mediatitle: "CooRadio ", city: "INTERNET RADIO", mediaid: 1854, logo: "/logos/gr/mini/cooradio.gif" }, 
{ mediatitle: "CosiRadio Int'l Station ", city: "INTERNET RADIO", mediaid: 1950, logo: "/logos/gr/mini/cosiradio.gif" }, 
{ mediatitle: "Cosmic Radio 102,6", city: "ΚΑΛΑΜΑΤΑ", mediaid: 988, logo: "/logos/gr/mini/cosmicradio.gif" }, 
{ mediatitle: "Cosmos Fm 103,8", city: "ΚΑΤΕΡΙΝΗ", mediaid: 900, logo: "/logos/gr/mini/cosmospieria.gif" }, 
{ mediatitle: "Cosmos Fm 89,6", city: "ΚΑΒΑΛΑ", mediaid: 1806, logo: "/logos/gr/mini/cosmos896.gif" }, 
{ mediatitle: "Creta Planet ", city: "INTERNET RADIO", mediaid: 685, logo: "/logos/gr/mini/cretaplanet.gif" }, 
{ mediatitle: "D.I.T. Radio ", city: "INTERNET RADIO", mediaid: 941, logo: "/logos/gr/mini/ditradio.gif" }, 
{ mediatitle: "Dalkas 88,2", city: "ΧΑΛΚΙΔΑ", mediaid: 296, logo: "/logos/gr/mini/dalkas.gif" }, 
{ mediatitle: "Dance Radio ", city: "INTERNET RADIO", mediaid: 678, logo: "/logos/gr/mini/danceradio.gif" }, 
{ mediatitle: "Dance Radio - ChillOut Channel ", city: "INTERNET RADIO", mediaid: 771, logo: "/logos/gr/mini/danceradio.gif" }, 
{ mediatitle: "Dance Radio - Tech House ", city: "INTERNET RADIO", mediaid: 677, logo: "/logos/gr/mini/danceradio.gif" }, 
{ mediatitle: "D-Code 96,2", city: "ΧΑΝΙΑ", mediaid: 314, logo: "/logos/gr/mini/dcode.gif" }, 
{ mediatitle: "Derti 98,6", city: "ΑΘΗΝΑ", mediaid: 468, logo: "/logos/gr/mini/derti.gif" }, 
{ mediatitle: "Derti Fm 104,9", city: "ΡΟΔΟΣ", mediaid: 693, logo: "/logos/gr/mini/dertifmdode.gif" }, 
{ mediatitle: "DiasNews ", city: "ΚΑΛΑΜΑΤΑ", mediaid: 1239, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Discomania ", city: "INTERNET RADIO", mediaid: 671, logo: "/logos/gr/mini/discomania.gif" }, 
{ mediatitle: "Diva Radio 91,6", city: "ΚΟΖΑΝΗ", mediaid: 448, logo: "/logos/gr/mini/divaradio.gif" }, 
{ mediatitle: "Dive Radio ", city: "INTERNET RADIO", mediaid: 883, logo: "/logos/gr/mini/diveradio.gif" }, 
{ mediatitle: "DJ Vasilis WebRadio ", city: "INTERNET RADIO", mediaid: 1943, logo: "/logos/gr/mini/djvasilis.gif" }, 
{ mediatitle: "Doggradio ", city: "INTERNET RADIO", mediaid: 56, logo: "/logos/gr/mini/doggradio.gif" }, 
{ mediatitle: "Dolce Radio 89,5", city: "ΒΟΛΟΣ", mediaid: 699, logo: "/logos/gr/mini/dolceradio.gif" }, 
{ mediatitle: "Donna Radio ", city: "INTERNET RADIO", mediaid: 1902, logo: "/logos/gr/mini/donnaradio.gif" }, 
{ mediatitle: "dRadio ", city: "ΛΑΡΙΣΑ", mediaid: 1886, logo: "/logos/gr/mini/dradio.gif" }, 
{ mediatitle: "Dream FM 91", city: "ΗΡΑΚΛΕΙΟ", mediaid: 53, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Dream Fm 103,5", city: "ΑΘΗΝΑ", mediaid: 519, logo: "/logos/gr/mini/dreamfm.gif" }, 
{ mediatitle: "Dream Radio ", city: "INTERNET RADIO", mediaid: 940, logo: "/logos/gr/mini/dreamradio.gif" }, 
{ mediatitle: "DRS 95,3", city: "ΗΡΑΚΛΕΙΟ", mediaid: 1090, logo: "/logos/gr/mini/drs953.gif" }, 
{ mediatitle: "Dynamic Web Radio ", city: "ΑΘΗΝΑ", mediaid: 1947, logo: "/logos/gr/mini/dynamicweb.gif" }, 
{ mediatitle: "Echoes ", city: "INTERNET RADIO", mediaid: 27, logo: "/logos/gr/mini/echoes.gif" }, 
{ mediatitle: "Electrocaine ", city: "INTERNET RADIO", mediaid: 845, logo: "/logos/gr/mini/electrocaine.gif" }, 
{ mediatitle: "Empneusi Radio ", city: "INTERNET RADIO", mediaid: 859, logo: "/logos/gr/mini/empneusi.gif" }, 
{ mediatitle: "Enallax Radio ", city: "INTERNET RADIO", mediaid: 1466, logo: "/logos/gr/mini/enallaxintradio.gif" }, 
{ mediatitle: "Energy 93,4", city: "ΠΡΕΒΕΖΑ", mediaid: 877, logo: "/logos/gr/mini/energy934.gif" }, 
{ mediatitle: "Energy Radio 88,9", city: "ΔΡΑΜΑ", mediaid: 785, logo: "/logos/gr/mini/nrgdramas.gif" }, 
{ mediatitle: "Epigee Radio ", city: "INTERNET RADIO", mediaid: 792, logo: "/logos/gr/mini/epigee.gif" }, 
{ mediatitle: "Erotokritos Fm 87,9", city: "ΗΡΑΚΛΕΙΟ", mediaid: 459, logo: "/logos/gr/mini/erotokritos.gif" }, 
{ mediatitle: "Eurovision.Fm ", city: "ΑΘΗΝΑ", mediaid: 4, logo: "/logos/gr/mini/eurovisionfm.gif" }, 
{ mediatitle: "Existon Radio ", city: "ΑΘΗΝΑ", mediaid: 1944, logo: "/logos/gr/mini/existon.gif" }, 
{ mediatitle: "Extreme Radio ", city: "INTERNET RADIO", mediaid: 1895, logo: "/logos/gr/mini/extremeradionet.gif" }, 
{ mediatitle: "Extreme Radio ", city: "INTERNET RADIO", mediaid: 1769, logo: "/logos/gr/mini/extremeradiogr.gif" }, 
{ mediatitle: "Face Fm ", city: "ΣΑΜΟΣ", mediaid: 171, logo: "/logos/gr/mini/FaceFm.gif" }, 
{ mediatitle: "FaceGreek WebRadio ", city: "INTERNET RADIO", mediaid: 1926, logo: "/logos/gr/mini/facegreek.gif" }, 
{ mediatitle: "Fever Radio 106,3", city: "ΚΟΖΑΝΗ", mediaid: 727, logo: "/logos/gr/mini/feverkoz.gif" }, 
{ mediatitle: "Flash 96", city: "ΑΘΗΝΑ", mediaid: 106, logo: "/logos/gr/mini/flash.gif" }, 
{ mediatitle: "Flippinradio ", city: "INTERNET RADIO", mediaid: 1892, logo: "/logos/gr/mini/flippin.gif" }, 
{ mediatitle: "Fly Fm 95,9", city: "ΡΕΘΥΜΝΟ", mediaid: 12, logo: "/logos/gr/mini/flyfm.gif" }, 
{ mediatitle: "Fly Radio 89,7", city: "ΣΠΑΡΤΗ", mediaid: 252, logo: "/logos/gr/mini/flyradio.gif" }, 
{ mediatitle: "FM100 100", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 694, logo: "/logos/gr/mini/fm100.gif" }, 
{ mediatitle: "Forbeaten ", city: "INTERNET RADIO", mediaid: 1935, logo: "/logos/gr/mini/forbeaten.gif" }, 
{ mediatitle: "free Angel 91,8", city: "ΑΘΗΝΑ", mediaid: 1776, logo: "/logos/gr/mini/freeangel918.gif" }, 
{ mediatitle: "Freedom Fm ", city: "ΑΘΗΝΑ", mediaid: 534, logo: "/logos/gr/mini/freedomfm.gif" }, 
{ mediatitle: "Fresh 88,6", city: "ΑΘΗΝΑ", mediaid: 85, logo: "/logos/gr/mini/fresh886.gif" }, 
{ mediatitle: "Fresh FM 92,9", city: "ΚΟΖΑΝΗ", mediaid: 1936, logo: "/logos/gr/mini/fresh929.gif" }, 
{ mediatitle: "Fresh Web Radio ", city: "INTERNET RADIO", mediaid: 931, logo: "/logos/gr/mini/freshwebradio.gif" }, 
{ mediatitle: "Fun Radio ", city: "INTERNET RADIO", mediaid: 848, logo: "/logos/gr/mini/funradio.gif" }, 
{ mediatitle: "Gaga Radio ", city: "ΚΕΡΚΥΡΑ", mediaid: 1763, logo: "/logos/gr/mini/gagaradio.gif" }, 
{ mediatitle: "Galaxy 92", city: "ΑΘΗΝΑ", mediaid: 99, logo: "/logos/gr/mini/galaxy92.gif" }, 
{ mediatitle: "Galaxy Fm 106,1", city: "ΠΑΤΡΑ", mediaid: 905, logo: "/logos/gr/mini/galaxy1061.gif" }, 
{ mediatitle: "Galaxy FM 101,1", city: "ΤΡΙΠΟΛΗ", mediaid: 1909, logo: "/logos/gr/mini/galaxy1011.gif" }, 
{ mediatitle: "Genesis FM ", city: "INTERNET RADIO", mediaid: 1850, logo: "/logos/gr/mini/genesisfm.gif" }, 
{ mediatitle: "Ghost Radio ", city: "INTERNET RADIO", mediaid: 1814, logo: "/logos/gr/mini/ghost.gif" }, 
{ mediatitle: "Ghs-Radio ", city: "INTERNET RADIO", mediaid: 866, logo: "/logos/gr/mini/ghsradio.gif" }, 
{ mediatitle: "Global Radio ", city: "ΤΡΙΠΟΛΗ", mediaid: 1824, logo: "/logos/gr/mini/globalgr.gif" }, 
{ mediatitle: "Gnet Radio ", city: "INTERNET RADIO", mediaid: 713, logo: "/logos/gr/mini/gradio.gif" }, 
{ mediatitle: "Gold10 Radio ", city: "ΒΟΛΟΣ", mediaid: 1879, logo: "/logos/gr/mini/gold10.gif" }, 
{ mediatitle: "Gorgona K1 ", city: "INTERNET RADIO", mediaid: 1830, logo: "/logos/gr/mini/gorgona.gif" }, 
{ mediatitle: "GR4U ", city: "DUSSELDORF", mediaid: 832, logo: "/logos/gr/mini/greek4u.gif" }, 
{ mediatitle: "GrassaGooGoo ", city: "INTERNET RADIO", mediaid: 212, logo: "/logos/gr/mini/grassagoogoo.gif" }, 
{ mediatitle: "Greca Fm 99,4", city: "ΠΥΡΓΟΣ", mediaid: 21, logo: "/logos/gr/mini/greca.gif" }, 
{ mediatitle: "happy dream radio ", city: "INTERNET RADIO", mediaid: 919, logo: "/logos/gr/mini/happydreamradio.gif" }, 
{ mediatitle: "Happy Radio 93,2", city: "ΑΘΗΝΑ", mediaid: 282, logo: "/logos/gr/mini/happy932.gif" }, 
{ mediatitle: "Heart 93,9", city: "ΧΑΛΚΙΔΑ", mediaid: 1789, logo: "/logos/gr/mini/heart939.gif" }, 
{ mediatitle: "Heart Fm 93,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 100, logo: "/logos/gr/mini/heartfm.gif" }, 
{ mediatitle: "Heat Radio 88,3", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 414, logo: "/logos/gr/mini/heatfm.gif" }, 
{ mediatitle: "HiJack ", city: "INTERNET RADIO", mediaid: 538, logo: "/logos/gr/mini/hijack.gif" }, 
{ mediatitle: "Hit FM 103,5", city: "ΧΑΛΚΙΔΑ", mediaid: 1211, logo: "/logos/gr/mini/hitfm1035.gif" }, 
{ mediatitle: "Horizon 96,5", city: "ΤΡΙΠΟΛΗ", mediaid: 446, logo: "/logos/gr/mini/horizon.gif" }, 
{ mediatitle: "Hot Fm ", city: "ΑΘΗΝΑ", mediaid: 963, logo: "/logos/gr/mini/hotfmathens.gif" }, 
{ mediatitle: "Hot Station ", city: "INTERNET RADIO", mediaid: 307, logo: "/logos/gr/mini/hotstation.gif" }, 
{ mediatitle: "HotMix 88", city: "ΤΡΙΚΑΛΑ", mediaid: 130, logo: "/logos/gr/mini/hotmix.gif" }, 
{ mediatitle: "Hxo Fm 102,7", city: "ΙΩΑΝΝΙΝΑ", mediaid: 894, logo: "/logos/gr/mini/hxoioan.gif" }, 
{ mediatitle: "Ianos Radio ", city: "INTERNET RADIO", mediaid: 937, logo: "/logos/gr/mini/ianosradio.gif" }, 
{ mediatitle: "IEK Delta Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 489, logo: "/logos/gr/mini/deltaradio.gif" }, 
{ mediatitle: "IEK Delta Radio - Alternative ", city: "ΑΘΗΝΑ", mediaid: 743, logo: "/logos/gr/mini/deltaradioalter.gif" }, 
{ mediatitle: "Imagine 89,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 762, logo: "/logos/gr/mini/imagine.gif" }, 
{ mediatitle: "In Athens Dance Radio ", city: "INTERNET RADIO", mediaid: 1859, logo: "/logos/gr/mini/inathensdance.gif" }, 
{ mediatitle: "In Athens Greek Radio ", city: "INTERNET RADIO", mediaid: 1860, logo: "/logos/gr/mini/inathensgreek.gif" }, 
{ mediatitle: "In Athens Radio ", city: "INTERNET RADIO", mediaid: 1818, logo: "/logos/gr/mini/inathens.gif" }, 
{ mediatitle: "In Athens Rock Radio ", city: "INTERNET RADIO", mediaid: 1861, logo: "/logos/gr/mini/inathensrock.gif" }, 
{ mediatitle: "International 107,5", city: "ΙΩΑΝΝΙΝΑ", mediaid: 839, logo: "/logos/gr/mini/international.gif" }, 
{ mediatitle: "Internet Radio Koziani ", city: "ΚΟΖΑΝΗ", mediaid: 1443, logo: "/logos/gr/mini/koziani.gif" }, 
{ mediatitle: "Intersonik ", city: "INTERNET RADIO", mediaid: 1901, logo: "/logos/gr/mini/intersonik.gif" }, 
{ mediatitle: "Involved Radio ", city: "ΠΕΙΡΑΙΑΣ", mediaid: 1962, logo: "/logos/gr/mini/involved.gif" }, 
{ mediatitle: "Island Fm 88,6", city: "ΖΑΚΥΝΘΟΣ", mediaid: 630, logo: "/logos/gr/mini/islandfm.gif" }, 
{ mediatitle: "Je t'aime 93,4", city: "ΑΘΗΝΑ", mediaid: 757, logo: "/logos/gr/mini/jetaime.gif" }, 
{ mediatitle: "Jesto's Radio ", city: "INTERNET RADIO", mediaid: 1758, logo: "/logos/gr/mini/jestos.gif" }, 
{ mediatitle: "JukeBox ", city: "INTERNET RADIO", mediaid: 202, logo: "/logos/gr/mini/jukebox.gif" }, 
{ mediatitle: "Just Radio 93", city: "ΧΑΛΚΙΔΑ", mediaid: 345, logo: "/logos/gr/mini/justradio.gif" }, 
{ mediatitle: "Just Radio 96,4", city: "ΚΟΡΙΝΘΟΣ", mediaid: 1920, logo: "/logos/gr/mini/justr964.gif" }, 
{ mediatitle: "Kiss 98", city: "ΒΟΛΟΣ", mediaid: 1843, logo: "/logos/gr/mini/kiss98.gif" }, 
{ mediatitle: "Kiss 100,4", city: "ΚΑΡΔΙΤΣΑ", mediaid: 1792, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Kiss 107", city: "ΟΡΕΣΤΙΑΔΑ", mediaid: 1793, logo: "/logos/gr/mini/kiss107orest.gif" }, 
{ mediatitle: "Kiss Danceradio ", city: "INTERNET RADIO", mediaid: 1930, logo: "/logos/gr/mini/kissdance.gif" }, 
{ mediatitle: "Kiss FM 89", city: "ΚΑΛΑΜΑΤΑ", mediaid: 1911, logo: "/logos/gr/mini/kissne89.gif" }, 
{ mediatitle: "Kiss Fm 92,9", city: "ΑΘΗΝΑ", mediaid: 114, logo: "/logos/gr/mini/kissfm.gif" }, 
{ mediatitle: "Kiss Fm 100,6", city: "ΚΕΦΑΛΛΟΝΙΑ", mediaid: 175, logo: "/logos/gr/mini/kisskefalonias.gif" }, 
{ mediatitle: "KissFm 96,1", city: "ΗΡΑΚΛΕΙΟ", mediaid: 237, logo: "/logos/gr/mini/kisscrete.gif" }, 
{ mediatitle: "KissFm 92,2", city: "ΠΑΤΡΑ", mediaid: 426, logo: "/logos/gr/mini/kiss922.gif" }, 
{ mediatitle: "KwsParty ", city: "ΚΩΣ", mediaid: 1938, logo: "/logos/gr/mini/kwsparty.gif" }, 
{ mediatitle: "Kλίμαξ Plus ", city: "INTERNET RADIO", mediaid: 948, logo: "/logos/gr/mini/klimaka.gif" }, 
{ mediatitle: "Lampsi Fm 92,9", city: "ΗΡΑΚΛΕΙΟ", mediaid: 691, logo: "/logos/gr/mini/lampsifmcrete.gif" }, 
{ mediatitle: "Lava Radio 107,7", city: "ΗΡΑΚΛΕΙΟ", mediaid: 522, logo: "/logos/gr/mini/lavaradio.gif" }, 
{ mediatitle: "Libero 107,4", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 208, logo: "/logos/gr/mini/liberofm.gif" }, 
{ mediatitle: "Libido Radio ", city: "INTERNET RADIO", mediaid: 951, logo: "/logos/gr/mini/libido.gif" }, 
{ mediatitle: "Life Fm 103,1", city: "ΞΥΛΟΚΑΣΤΡΟ", mediaid: 436, logo: "/logos/gr/mini/xylokastro.gif" }, 
{ mediatitle: "Life Radio 102,9", city: "ΚΕΡΚΥΡΑ", mediaid: 425, logo: "/logos/gr/mini/liferadio1029.gif" }, 
{ mediatitle: "Live 89,6", city: "ΧΑΛΚΙΔΑ", mediaid: 76, logo: "/logos/gr/mini/livefm.gif" }, 
{ mediatitle: "Loco Radio ", city: "ΑΘΗΝΑ", mediaid: 793, logo: "/logos/gr/mini/loco.gif" }, 
{ mediatitle: "Loud Radio 88,8", city: "ΤΡΙΚΑΛΑ", mediaid: 131, logo: "/logos/gr/mini/loudfm.gif" }, 
{ mediatitle: "Lounge MotionFm ", city: "INTERNET RADIO", mediaid: 503, logo: "/logos/gr/mini/loungemotion.gif" }, 
{ mediatitle: "Love Radio 97,5", city: "ΑΘΗΝΑ", mediaid: 287, logo: "/logos/gr/mini/loveradio.gif" }, 
{ mediatitle: "Love Radio 97,2", city: "ΙΩΑΝΝΙΝΑ", mediaid: 962, logo: "/logos/gr/mini/loveioan.gif" }, 
{ mediatitle: "Mad Radio 106,2", city: "ΑΘΗΝΑ", mediaid: 484, logo: "/logos/gr/mini/madradio.gif" }, 
{ mediatitle: "Maelli Radio ", city: "INTERNET RADIO", mediaid: 1838, logo: "/logos/gr/mini/maelli.gif" }, 
{ mediatitle: "Magia Fm ", city: "ΑΣΤΑΚΟΣ", mediaid: 899, logo: "/logos/gr/mini/magiafm.gif" }, 
{ mediatitle: "Magic Fm 98,2", city: "ΧΑΝΙΑ", mediaid: 193, logo: "/logos/gr/mini/magicfm.gif" }, 
{ mediatitle: "Magic FM Αγρίνιο ", city: "ΑΓΡΙΝΙΟ", mediaid: 1772, logo: "/logos/gr/mini/magicagrin.gif" }, 
{ mediatitle: "Mandra Radio ", city: "INTERNET RADIO", mediaid: 1764, logo: "/logos/gr/mini/mandra.gif" }, 
{ mediatitle: "Mango Radio Urban ", city: "INTERNET RADIO", mediaid: 218, logo: "/logos/gr/mini/mangoradio.gif" }, 
{ mediatitle: "Maroni ", city: "INTERNET RADIO", mediaid: 949, logo: "/logos/gr/mini/maroni.gif" }, 
{ mediatitle: "Mathimatikos Web Radio ", city: "INTERNET RADIO", mediaid: 1904, logo: "/logos/gr/mini/mathematikos.gif" }, 
{ mediatitle: "Max FM 93,4", city: "ΠΑΤΡΑ", mediaid: 1160, logo: "/logos/gr/mini/maxfm934.gif" }, 
{ mediatitle: "Max Fm 92,5", city: "ΗΡΑΚΛΕΙΟ", mediaid: 788, logo: "/logos/gr/mini/max925.gif" }, 
{ mediatitle: "Max Fm 100,2", city: "ΧΑΝΙΑ", mediaid: 355, logo: "/logos/gr/mini/maxcrete.gif" }, 
{ mediatitle: "Maximum FM 93,6", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 310, logo: "/logos/gr/mini/maxfm.gif" }, 
{ mediatitle: "MAXRADIO ", city: "INTERNET RADIO", mediaid: 1893, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Media 92", city: "ΣΥΡΟΣ", mediaid: 648, logo: "/logos/gr/mini/media92.gif" }, 
{ mediatitle: "Melodia Εντεχνο ", city: "ΛΕΥΚΩΣΙΑ", mediaid: 471, logo: "/logos/cy/mini/melodiacy.gif" }, 
{ mediatitle: "Melody Fm 98,7", city: "ΗΡΑΚΛΕΙΟ", mediaid: 341, logo: "/logos/gr/mini/melodyfm.gif" }, 
{ mediatitle: "Metal Zone ", city: "INTERNET RADIO", mediaid: 73, logo: "/logos/gr/mini/metalzone.gif" }, 
{ mediatitle: "Metro Fm 90,3", city: "ΛΑΜΙΑ", mediaid: 198, logo: "/logos/gr/mini/metro903.gif" }, 
{ mediatitle: "Metro FM 101,2", city: "ΧΑΛΚΙΔΑ", mediaid: 1593, logo: "/logos/gr/mini/metro1012.gif" }, 
{ mediatitle: "Metro Radio 89,2", city: "ΗΡΑΚΛΕΙΟ", mediaid: 61, logo: "/logos/gr/mini/metroradio.gif" }, 
{ mediatitle: "Metropolis 95,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 110, logo: "/logos/gr/mini/metropolis.gif" }, 
{ mediatitle: "Mfm 102,7", city: "ΠΑΤΡΑ", mediaid: 1846, logo: "/logos/gr/mini/mfm1027.gif" }, 
{ mediatitle: "Midnight Blues ", city: "INTERNET RADIO", mediaid: 933, logo: "/logos/gr/mini/midnightblues.gif" }, 
{ mediatitle: "Midnight Radio ", city: "INTERNET RADIO", mediaid: 1916, logo: "/logos/gr/mini/midnightradio.gif" }, 
{ mediatitle: "Mind Radio Conn-X ", city: "INTERNET RADIO", mediaid: 667, logo: "/logos/gr/mini/mindradio.gif" }, 
{ mediatitle: "Mini FM 107,1", city: "ΚΡΕΣΤΕΝΑ", mediaid: 1910, logo: "/logos/gr/mini/mini1071.gif" }, 
{ mediatitle: "Mix Fm 102,2", city: "ΓΡΕΒΕΝΑ", mediaid: 184, logo: "/logos/gr/mini/mixgrevena.gif" }, 
{ mediatitle: "Mojo Radio 107,7", city: "ΠΑΤΡΑ", mediaid: 172, logo: "/logos/gr/mini/mojoradio.gif" }, 
{ mediatitle: "Mood Radio ", city: "INTERNET RADIO", mediaid: 924, logo: "/logos/gr/mini/moodradiio.gif" }, 
{ mediatitle: "Moreradio ", city: "ΑΘΗΝΑ", mediaid: 1795, logo: "/logos/gr/mini/moreradio.gif" }, 
{ mediatitle: "Motion Fm ", city: "INTERNET RADIO", mediaid: 401, logo: "/logos/gr/mini/motionfm.gif" }, 
{ mediatitle: "Mr Soul ", city: "INTERNET RADIO", mediaid: 878, logo: "/logos/gr/mini/mrsoul.gif" }, 
{ mediatitle: "Music 89,2", city: "ΑΘΗΝΑ", mediaid: 820, logo: "/logos/gr/mini/music892new.gif" }, 
{ mediatitle: "Music Art Club ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 885, logo: "/logos/gr/mini/musicartclub.gif" }, 
{ mediatitle: "Music Box 106,5", city: "ΧΑΝΙΑ", mediaid: 805, logo: "/logos/gr/mini/musicbox.gif" }, 
{ mediatitle: "Music Club 105,8", city: "ΗΡΑΚΛΕΙΟ", mediaid: 438, logo: "/logos/gr/mini/musicclub.gif" }, 
{ mediatitle: "Music Heaven ", city: "INTERNET RADIO", mediaid: 675, logo: "/logos/gr/mini/musicheaven.gif" }, 
{ mediatitle: "Music Lovers ", city: "INTERNET RADIO", mediaid: 1821, logo: "/logos/gr/mini/musiclovers.gif" }, 
{ mediatitle: "Music Mania ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 861, logo: "/logos/gr/mini/musicmania.gif" }, 
{ mediatitle: "MusicRadio.Gr ", city: "ΑΘΗΝΑ", mediaid: 1796, logo: "/logos/gr/mini/musicradiogr.gif" }, 
{ mediatitle: "MUSICVOICE FM ", city: "ΑΘΗΝΑ", mediaid: 1825, logo: "/logos/gr/mini/musicvoice.gif" }, 
{ mediatitle: "M-Word Web Radio ", city: "INTERNET RADIO", mediaid: 1929, logo: "/logos/gr/mini/mwordr.gif" }, 
{ mediatitle: "My Radio 89,6", city: "ΚΟΡΙΝΘΟΣ", mediaid: 817, logo: "/logos/gr/mini/myradionet.gif" }, 
{ mediatitle: "Nasos Radio ", city: "INTERNET RADIO", mediaid: 835, logo: "/logos/gr/mini/nasosradio.gif" }, 
{ mediatitle: "Nautilus Radio ", city: "ΧΑΝΙΑ", mediaid: 821, logo: "/logos/gr/mini/nautilus.gif" }, 
{ mediatitle: "Navagia.gr ", city: "INTERNET RADIO", mediaid: 1852, logo: "/logos/gr/mini/navagiagr.gif" }, 
{ mediatitle: "Netcruise Radio ", city: "INTERNET RADIO", mediaid: 929, logo: "/logos/gr/mini/netcruiseradio.gif" }, 
{ mediatitle: "Nexus Productions Radio ", city: "INTERNET RADIO", mediaid: 1817, logo: "/logos/gr/mini/nexus.gif" }, 
{ mediatitle: "Nitro Radio 102,5", city: "ΑΘΗΝΑ", mediaid: 144, logo: "/logos/gr/mini/nitro.gif" }, 
{ mediatitle: "Noise Fm 100,5", city: "ΛΑΜΙΑ", mediaid: 138, logo: "/logos/gr/mini/noiselamia.gif" }, 
{ mediatitle: "Noise Radio 97,8", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 1797, logo: "/logos/gr/mini/noise978.gif" }, 
{ mediatitle: "Noize Radio 93,5", city: "ΣΕΡΡΕΣ", mediaid: 224, logo: "/logos/gr/mini/noizeradio.gif" }, 
{ mediatitle: "Nova Radio 93,1", city: "ΞΑΝΘΗ", mediaid: 546, logo: "/logos/gr/mini/novamusic.gif" }, 
{ mediatitle: "Nova Sport Fm 94,6", city: "ΑΘΗΝΑ", mediaid: 145, logo: "/logos/gr/mini/novasportfm.gif" }, 
{ mediatitle: "Novel 91,8", city: "ΚΟΡΙΝΘΟΣ", mediaid: 1922, logo: "/logos/gr/mini/novel918.gif" }, 
{ mediatitle: "Now Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1182, logo: "/logos/gr/mini/nowradio.gif" }, 
{ mediatitle: "Nrg Fm 95", city: "ΧΑΛΚΙΔΑ", mediaid: 512, logo: "/logos/gr/mini/nrgfm.gif" }, 
{ mediatitle: "NRG Radio 89,5", city: "ΚΟΖΑΝΗ", mediaid: 686, logo: "/logos/gr/mini/nrgkozanis.gif" }, 
{ mediatitle: "Nότες FM 106", city: "ΣΕΡΡΕΣ", mediaid: 1203, logo: "/logos/gr/mini/notesserres.gif" }, 
{ mediatitle: "Oasis Fm 88", city: "ΑΘΗΝΑ", mediaid: 431, logo: "/logos/gr/mini/oasis.gif" }, 
{ mediatitle: "OFF Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 809, logo: "/logos/gr/mini/offradio.gif" }, 
{ mediatitle: "Ola Fm 91,4", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 457, logo: "/logos/gr/mini/olafm.gif" }, 
{ mediatitle: "Omorfi Poli 89,9", city: "ΞΑΝΘΗ", mediaid: 115, logo: "/logos/gr/mini/omorfipoli.gif" }, 
{ mediatitle: "Onar Radio ", city: "INTERNET RADIO", mediaid: 1885, logo: "/logos/gr/mini/onarradio.gif" }, 
{ mediatitle: "Original 94,4", city: "ΧΑΝΙΑ", mediaid: 1108, logo: "/logos/gr/mini/original944.gif" }, 
{ mediatitle: "ORT 92,3", city: "ΠΥΡΓΟΣ", mediaid: 507, logo: "/logos/gr/mini/ort.gif" }, 
{ mediatitle: "Oscar FM 90,9", city: "ΛΑΜΙΑ", mediaid: 1765, logo: "/logos/gr/mini/oscar909.gif" }, 
{ mediatitle: "Paradise 90,3", city: "ΞΑΝΘΗ", mediaid: 169, logo: "/logos/gr/mini/paradise.gif" }, 
{ mediatitle: "Paradise Radio 104,6", city: "ΑΘΗΝΑ", mediaid: 662, logo: "/logos/gr/mini/paradiseradio.gif" }, 
{ mediatitle: "Party 97,1", city: "ΕΛΑΣΣOΝΑ", mediaid: 1798, logo: "/logos/gr/mini/party971.gif" }, 
{ mediatitle: "Phase Radio 87,7", city: "ΛΑΜΙΑ", mediaid: 359, logo: "/logos/gr/mini/phaseradio.gif" }, 
{ mediatitle: "Piqeras Deejay 105,6", city: "ΑΘΗΝΑ", mediaid: 140, logo: "/logos/gr/mini/piqerasdj.gif" }, 
{ mediatitle: "Pirate Radio 91", city: "ΧΙΟΣ", mediaid: 311, logo: "/logos/gr/mini/pirateradio.gif" }, 
{ mediatitle: "Piratis Radio ", city: "INTERNET RADIO", mediaid: 1953, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Plaisio Radio ", city: "INTERNET RADIO", mediaid: 389, logo: "/logos/gr/mini/plaisioradio.gif" }, 
{ mediatitle: "Plus Live ", city: "INTERNET RADIO", mediaid: 847, logo: "/logos/gr/mini/pluslive.gif" }, 
{ mediatitle: "Plus Radio 102,6", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 780, logo: "/logos/gr/mini/plusradio.gif" }, 
{ mediatitle: "PlusDj ", city: "INTERNET RADIO", mediaid: 709, logo: "/logos/gr/mini/plusdj.gif" }, 
{ mediatitle: "Polis 102,6", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 536, logo: "/logos/gr/mini/polis.gif" }, 
{ mediatitle: "PolyteXneio FM ", city: "INTERNET RADIO", mediaid: 1951, logo: "/logos/gr/mini/polytexneio.gif" }, 
{ mediatitle: "Pop Fm 102,1", city: "ΚΕΡΚΥΡΑ", mediaid: 173, logo: "/logos/gr/mini/popfm.gif" }, 
{ mediatitle: "Pop-I ", city: "INTERNET RADIO", mediaid: 914, logo: "/logos/gr/mini/popi.gif" }, 
{ mediatitle: "Post Rocking ", city: "INTERNET RADIO", mediaid: 863, logo: "/logos/gr/mini/postrocking.gif" }, 
{ mediatitle: "Power Fm 100,2", city: "ΒΟΛΟΣ", mediaid: 170, logo: "/logos/gr/mini/powervolos.gif" }, 
{ mediatitle: "Power FM 92,6", city: "ΚΟΖΑΝΗ", mediaid: 629, logo: "/logos/gr/mini/power926.gif" }, 
{ mediatitle: "Power Fm 93,2", city: "ΛΑΡΙΣΑ", mediaid: 453, logo: "/logos/gr/mini/powerfm.gif" }, 
{ mediatitle: "Prime Radio 100,3", city: "ΣΥΡΟΣ", mediaid: 183, logo: "/logos/gr/mini/primetime.gif" }, 
{ mediatitle: "Ps Radio ", city: "INTERNET RADIO", mediaid: 1207, logo: "/logos/gr/mini/psradio.gif" }, 
{ mediatitle: "Psycho Radio ", city: "INTERNET RADIO", mediaid: 927, logo: "/logos/gr/mini/psychoradio.gif" }, 
{ mediatitle: "Public Radio ", city: "ΚΑΛΑΜΑΤΑ", mediaid: 1882, logo: "/logos/gr/mini/publicradiogr.gif" }, 
{ mediatitle: "Radio 1 101", city: "ΣΕΡΡΕΣ", mediaid: 661, logo: "/logos/gr/mini/radio1serres.gif" }, 
{ mediatitle: "Radio 1 88", city: "ΡΟΔΟΣ", mediaid: 98, logo: "/logos/gr/mini/Radioena.gif" }, 
{ mediatitle: "Radio 1 Dance ", city: "ΡΟΔΟΣ", mediaid: 903, logo: "/logos/gr/mini/RadioOne.gif" }, 
{ mediatitle: "Radio 10 ", city: "INTERNET RADIO", mediaid: 1946, logo: "/logos/gr/mini/radio10.gif" }, 
{ mediatitle: "Radio 6 95,4", city: "ΞΑΝΘΗ", mediaid: 344, logo: "/logos/gr/mini/radio6x.gif" }, 
{ mediatitle: "RADIO 9 98,9", city: "ΑΘΗΝΑ", mediaid: 104, logo: "/logos/gr/mini/radio9ath.gif" }, 
{ mediatitle: "Radio 984 ", city: "ΗΡΑΚΛΕΙΟ", mediaid: 123, logo: "/logos/gr/mini/radio984.gif" }, 
{ mediatitle: "Radio Active 91,3", city: "ΣΙΦΝΟΣ", mediaid: 241, logo: "/logos/gr/mini/radioactive.gif" }, 
{ mediatitle: "Radio Apodrasi ", city: "INTERNET RADIO", mediaid: 932, logo: "/logos/gr/mini/radioapodrasi.gif" }, 
{ mediatitle: "Radio Argos Orestiko 97,4", city: "ΑΡΓΟΣ ΟΡΕΣΤΙΚΟ", mediaid: 528, logo: "/logos/gr/mini/orestidos.gif" }, 
{ mediatitle: "Radio Art 1 ", city: "INTERNET RADIO", mediaid: 935, logo: "/logos/gr/mini/radioart.gif" }, 
{ mediatitle: "Radio Art 2 ", city: "INTERNET RADIO", mediaid: 936, logo: "/logos/gr/mini/radioart.gif" }, 
{ mediatitle: "Radio Cancelled  ", city: "ΑΘΗΝΑ", mediaid: 1954, logo: "/logos/gr/mini/cancelled.gif" }, 
{ mediatitle: "Radio City 102,8", city: "ΚΑΤΕΡΙΝΗ", mediaid: 1937, logo: "/logos/gr/mini/rcity1028.gif" }, 
{ mediatitle: "Radio DriverFm ", city: "INTERNET RADIO", mediaid: 857, logo: "/logos/gr/mini/radiodriver.gif" }, 
{ mediatitle: "Radio ENA 87,6", city: "INTERNET RADIO", mediaid: 1799, logo: "/logos/gr/mini/radioenaau.gif" }, 
{ mediatitle: "Radio Energy 96,6", city: "ΚΑΒΑΛΑ", mediaid: 299, logo: "/logos/gr/mini/energy988.gif" }, 
{ mediatitle: "Radio Evros 97,1", city: "ΟΡΕΣΤΙΑΔΑ", mediaid: 504, logo: "/logos/gr/mini/radioevros.gif" }, 
{ mediatitle: "Radio Faros 105,9", city: "ΣΑΝΤΟΡΙΝΗ", mediaid: 754, logo: "/logos/gr/mini/ant1santorinis.gif" }, 
{ mediatitle: "Radio Fever ", city: "INTERNET RADIO", mediaid: 850, logo: "/logos/gr/mini/radiofever.gif" }, 
{ mediatitle: "Radio Gold ", city: "ΑΘΗΝΑ", mediaid: 101, logo: "/logos/gr/mini/Gold.gif" }, 
{ mediatitle: "Radio Heaven ", city: "INTERNET RADIO", mediaid: 1918, logo: "/logos/gr/mini/radioheaven.gif" }, 
{ mediatitle: "Radio Hersonissos 97,2", city: "ΗΡΑΚΛΕΙΟ", mediaid: 460, logo: "/logos/gr/mini/Hersonissos.gif" }, 
{ mediatitle: "RADIO KIMA : WKMA ", city: "INTERNET RADIO", mediaid: 1771, logo: "/logos/gr/mini/kimawkma.gif" }, 
{ mediatitle: "Radio Mania ", city: "INTERNET RADIO", mediaid: 1856, logo: "/logos/gr/mini/radiomaniagr.gif" }, 
{ mediatitle: "Radio Mastixa 107,7", city: "ΧΙΟΣ", mediaid: 498, logo: "/logos/gr/mini/radiomastixa.gif" }, 
{ mediatitle: "Radio Mora ", city: "INTERNET RADIO", mediaid: 1767, logo: "/logos/gr/mini/radiomora.gif" }, 
{ mediatitle: "Radio Mostra ", city: "INTERNET RADIO", mediaid: 1702, logo: "/logos/cy/mini/mostra.gif" }, 
{ mediatitle: "Radio Must Athens ", city: "INTERNET RADIO", mediaid: 1899, logo: "/logos/gr/mini/mustathens.gif" }, 
{ mediatitle: "Radio Net 101,9", city: "ΛΑΜΙΑ", mediaid: 201, logo: "/logos/gr/mini/radionetlamia.gif" }, 
{ mediatitle: "Radio Olympos ", city: "ΚΑΡΠΑΘΟΣ", mediaid: 1836, logo: "/logos/gr/mini/radioolympos.gif" }, 
{ mediatitle: "Radio Patata ", city: "INTERNET RADIO", mediaid: 1948, logo: "/logos/gr/mini/patata.gif" }, 
{ mediatitle: "Radio Planet 90,6", city: "ΙΕΡΑΠΕΤΡΑ", mediaid: 70, logo: "/logos/gr/mini/planetradio.gif" }, 
{ mediatitle: "Radio Point ", city: "INTERNET RADIO", mediaid: 62, logo: "/logos/gr/mini/radiopoint.gif" }, 
{ mediatitle: "Radio Star 95,5", city: "ΝΕΑ ΜΟΥΔΑΝΙΑ", mediaid: 908, logo: "/logos/gr/mini/star955.gif" }, 
{ mediatitle: "Radio Thesprotia 97,2", city: "ΠΑΡΑΜΥΘΙΑ", mediaid: 521, logo: "/logos/gr/mini/radiothesprotia.gif" }, 
{ mediatitle: "Radio YET ", city: "INTERNET RADIO", mediaid: 1828, logo: "/logos/gr/mini/radioyet.gif" }, 
{ mediatitle: "Radio Ακρίτες 102,3", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 423, logo: "/logos/gr/mini/akrites.gif" }, 
{ mediatitle: "Radio Αναγέννηση ", city: "INTERNET RADIO", mediaid: 801, logo: "/logos/gr/mini/anagennisi.gif" }, 
{ mediatitle: "Radio Βελίκα 92,2", city: "ΛΑΡΙΣΑ", mediaid: 422, logo: "/logos/gr/mini/radiovelika.gif" }, 
{ mediatitle: "Radio Ε.Μ.Σ.Ε. ", city: "INTERNET RADIO", mediaid: 852, logo: "/logos/gr/mini/radioemse.gif" }, 
{ mediatitle: "Radio Ελασσώνα 88,4", city: "ΕΛΑΣΣOΝΑ", mediaid: 412, logo: "/logos/gr/mini/elassona.gif" }, 
{ mediatitle: "Radio Ενταση 93,5", city: "ΧΑΝΙΑ", mediaid: 209, logo: "/logos/gr/mini/radioentasi.gif" }, 
{ mediatitle: "Radio Πάτρα 106,5", city: "ΠΑΤΡΑ", mediaid: 716, logo: "/logos/gr/mini/radiopatra.gif" }, 
{ mediatitle: "Radio Ριζίτες 92,4", city: "ΚΑΣΤΕΛI", mediaid: 525, logo: "/logos/gr/mini/rizites.gif" }, 
{ mediatitle: "Radio Σαμοθράκη 101,9", city: "ΣΑΜΟΘΡΑΚΗ", mediaid: 526, logo: "/logos/gr/mini/radiosamothraki.gif" }, 
{ mediatitle: "RadioFREAKme ", city: "INTERNET RADIO", mediaid: 1750, logo: "/logos/gr/mini/freakme.gif" }, 
{ mediatitle: "RadioIn Λαϊκό ", city: "INTERNET RADIO", mediaid: 913, logo: "/logos/gr/mini/radioinlaiko.gif" }, 
{ mediatitle: "Rainbow 89", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 92, logo: "/logos/gr/mini/rainbow.gif" }, 
{ mediatitle: "Real Fm 107,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1778, logo: "/logos/gr/mini/realfmthess.gif" }, 
{ mediatitle: "Real Fm 97,8", city: "ΑΘΗΝΑ", mediaid: 680, logo: "/logos/gr/mini/realfm.gif" }, 
{ mediatitle: "Red 96,3", city: "ΑΘΗΝΑ", mediaid: 102, logo: "/logos/gr/mini/Red.gif" }, 
{ mediatitle: "Relax Fm 88,2", city: "ΠΑΤΡΑ", mediaid: 269, logo: "/logos/gr/mini/relaxfm882.gif" }, 
{ mediatitle: "Republic 100,3", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 478, logo: "/logos/gr/mini/republic.gif" }, 
{ mediatitle: "Retro Radio 105,4", city: "ΧΑΝΙΑ", mediaid: 449, logo: "/logos/gr/mini/retroradio.gif" }, 
{ mediatitle: "Rock Fm 96,9", city: "ΑΘΗΝΑ", mediaid: 96, logo: "/logos/gr/mini/rockfm.gif" }, 
{ mediatitle: "Rock Machine ", city: "INTERNET RADIO", mediaid: 683, logo: "/logos/gr/mini/rockmachine.gif" }, 
{ mediatitle: "Rock Radio 104,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 136, logo: "/logos/gr/mini/rockradio.gif" }, 
{ mediatitle: "Rock Velvet ", city: "INTERNET RADIO", mediaid: 1881, logo: "/logos/gr/mini/rockvelvetgr.gif" }, 
{ mediatitle: "Rockarolla Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1104, logo: "/logos/gr/mini/rockarolla.gif" }, 
{ mediatitle: "Rockgenesis.gr ", city: "INTERNET RADIO", mediaid: 1887, logo: "/logos/gr/mini/rockgenesis.gif" }, 
{ mediatitle: "Rodos Fm 90,7", city: "ΡΟΔΟΣ", mediaid: 430, logo: "/logos/gr/mini/rodosfm.gif" }, 
{ mediatitle: "RSA 91,1", city: "ΑΜΑΛΙΑΔΑ", mediaid: 465, logo: "/logos/gr/mini/rsa.gif" }, 
{ mediatitle: "RSO 91,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 413, logo: "/logos/gr/mini/rso.gif" }, 
{ mediatitle: "Safari 104,7", city: "ΙΩΑΝΝΙΝΑ", mediaid: 736, logo: "/logos/gr/mini/safari1047.gif" }, 
{ mediatitle: "Seal Radio ", city: "INTERNET RADIO", mediaid: 1955, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Sentra Fm 103,3", city: "ΑΘΗΝΑ", mediaid: 841, logo: "/logos/gr/mini/sendrafm.gif" }, 
{ mediatitle: "Sfera 94,1", city: "ΝΑΥΠΛΙΟ", mediaid: 904, logo: "/logos/gr/mini/sferaargolida.gif" }, 
{ mediatitle: "Sfera 96,6", city: "ΠΑΤΡΑ", mediaid: 270, logo: "/logos/gr/mini/sfera966.gif" }, 
{ mediatitle: "Sfera 102,2", city: "ΑΘΗΝΑ", mediaid: 143, logo: "/logos/gr/mini/sfera.gif" }, 
{ mediatitle: "Sferikos 99,3", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 182, logo: "/logos/gr/mini/feres.gif" }, 
{ mediatitle: "Shaker Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 26, logo: "/logos/gr/mini/shaker.gif" }, 
{ mediatitle: "Sick Radio ", city: "INTERNET RADIO", mediaid: 1712, logo: "/logos/gr/mini/sickradio.gif" }, 
{ mediatitle: "Skordo Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1957, logo: "/logos/gr/mini/skordo.gif" }, 
{ mediatitle: "Sky FM 91,3", city: "ΡΕΘΥΜΝΟ", mediaid: 1766, logo: "/logos/gr/mini/sky913fm.gif" }, 
{ mediatitle: "Sky Fm 99,7", city: "ΠΤΟΛEΜΑΙΔΑ", mediaid: 688, logo: "/logos/gr/mini/skyptolem.gif" }, 
{ mediatitle: "Sky Fm 100,7", city: "ΟΡΕΣΤΙΑΔΑ", mediaid: 520, logo: "/logos/gr/mini/skyfm1007.gif" }, 
{ mediatitle: "Sky Radio 99,2", city: "ΙΩΑΝΝΙΝΑ", mediaid: 142, logo: "/logos/gr/mini/skyradio992.gif" }, 
{ mediatitle: "SmartFm 100,7", city: "ΠΑΤΡΑ", mediaid: 427, logo: "/logos/gr/mini/smartfm.gif" }, 
{ mediatitle: "Smooth Traxx ", city: "INTERNET RADIO", mediaid: 700, logo: "/logos/gr/mini/smoothtraxx.gif" }, 
{ mediatitle: "Sok Fm 104,8", city: "ΧΑΛΚΙΔΑ", mediaid: 213, logo: "/logos/gr/mini/sokfm.gif" }, 
{ mediatitle: "Solid Radio ", city: "INTERNET RADIO", mediaid: 1956, logo: "/logos/gr/mini/solidradio.gif" }, 
{ mediatitle: "Space FM 107", city: "ΑΓΡΙΝΙΟ", mediaid: 1942, logo: "/logos/gr/mini/spaceagrinio.gif" }, 
{ mediatitle: "Space Fm 107,5", city: "ΝΑΞΟΣ", mediaid: 243, logo: "/logos/gr/mini/spacefmcyclades.gif" }, 
{ mediatitle: "Splash Radio ", city: "INTERNET RADIO", mediaid: 1703, logo: "/logos/gr/mini/splashradiogr.gif" }, 
{ mediatitle: "Sport 103", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 221, logo: "/logos/gr/mini/sport103.gif" }, 
{ mediatitle: "Sport FM 89,5", city: "ΒΟΛΟΣ", mediaid: 1801, logo: "/logos/gr/mini/sportfmvolos.gif" }, 
{ mediatitle: "Sport Fm 103,3", city: "ΡΕΘΥΜΝΟ", mediaid: 829, logo: "/logos/gr/mini/sportfmrethymno.gif" }, 
{ mediatitle: "SRadio ", city: "INTERNET RADIO", mediaid: 1655, logo: "/logos/gr/mini/sradio.gif" }, 
{ mediatitle: "Star 88,4", city: "ΗΡΑΚΛΕΙΟ", mediaid: 954, logo: "/logos/gr/mini/star884.gif" }, 
{ mediatitle: "Star 95,7", city: "ΙΩΑΝΝΙΝΑ", mediaid: 1841, logo: "/logos/gr/mini/star957.gif" }, 
{ mediatitle: "Star Fm 95,7", city: "ΙΩΑΝΝΙΝΑ", mediaid: 1878, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Star Fm 93,3", city: "ΓΡΕΒΕΝΑ", mediaid: 207, logo: "/logos/gr/mini/starfmdm.gif" }, 
{ mediatitle: "Star Fm 97,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 94, logo: "/logos/gr/mini/starfm.gif" }, 
{ mediatitle: "Star Fm 92,9", city: "ΝΑΥΠΛΙΟ", mediaid: 480, logo: "/logos/gr/mini/star929.gif" }, 
{ mediatitle: "Star Fm Κέρκυρα 88,8", city: "ΚΕΡΚΥΡΑ", mediaid: 126, logo: "/logos/gr/mini/star888.gif" }, 
{ mediatitle: "Star Fm Λαμία 97,1", city: "ΛΑΜΙΑ", mediaid: 210, logo: "/logos/gr/mini/starfmlamia.gif" }, 
{ mediatitle: "Star Fm Σπάρτη 94,1", city: "ΣΠΑΡΤΗ", mediaid: 15, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Star Radio 107,8", city: "ΣΥΜΗ", mediaid: 298, logo: "/logos/gr/mini/starradio1078.gif" }, 
{ mediatitle: "Star Radio 99", city: "ΧΑΛΚΙΔΑ", mediaid: 761, logo: "/logos/gr/mini/star99.gif" }, 
{ mediatitle: "Star Radio 106,7", city: "ΣΥΜΗ", mediaid: 1827, logo: "/logos/gr/mini/starsymi.gif" }, 
{ mediatitle: "Starwalkers New Generation ", city: "INTERNET RADIO", mediaid: 1945, logo: "/logos/gr/mini/starwalkersng.gif" }, 
{ mediatitle: "Starwalkers Radio ", city: "INTERNET RADIO", mediaid: 1877, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Status 94,2", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 873, logo: "/logos/gr/mini/statusradio.gif" }, 
{ mediatitle: "Steezy Radio ", city: "INTERNET RADIO", mediaid: 1896, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Sto Kokkino 105,5", city: "ΑΘΗΝΑ", mediaid: 415, logo: "/logos/gr/mini/kokkino.gif" }, 
{ mediatitle: "Studio 98", city: "ΡΕΘΥΜΝΟ", mediaid: 490, logo: "/logos/gr/mini/studio980.gif" }, 
{ mediatitle: "Studio 3 103,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 491, logo: "/logos/gr/mini/studio3.gif" }, 
{ mediatitle: "Studio 54 ", city: "ΑΘΗΝΑ", mediaid: 947, logo: "/logos/gr/mini/studio54.gif" }, 
{ mediatitle: "Studio E 103", city: "ΙΩΑΝΝΙΝΑ", mediaid: 752, logo: "/logos/gr/mini/studioe.gif" }, 
{ mediatitle: "Studio Fm1 105,4", city: "ΗΡΑΚΛΕΙΟ", mediaid: 19, logo: "/logos/gr/mini/teifm1.gif" }, 
{ mediatitle: "Studio Λευκάτας 90,5", city: "ΛΕΥΚΑΔΑ", mediaid: 185, logo: "/logos/gr/mini/lefkada.gif" }, 
{ mediatitle: "Style 100", city: "ΣHΤΕΙΑ", mediaid: 509, logo: "/logos/gr/mini/style100.gif" }, 
{ mediatitle: "Style Fm 89,6", city: "ΑΡΓΟΣ", mediaid: 256, logo: "/logos/gr/mini/stylefm.gif" }, 
{ mediatitle: "Stylida Fm 94,1", city: "ΛΑΜΙΑ", mediaid: 46, logo: "/logos/gr/mini/stylidafm.gif" }, 
{ mediatitle: "Sun Radio 97,1", city: "ΔΡΑΜΑ", mediaid: 518, logo: "/logos/gr/mini/sunradio.gif" }, 
{ mediatitle: "Sunshine Fm 107,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 529, logo: "/logos/gr/mini/sunshine1077.gif" }, 
{ mediatitle: "Super 88", city: "ΞΑΝΘΗ", mediaid: 958, logo: "/logos/gr/mini/super88.gif" }, 
{ mediatitle: "Super FM 89,6", city: "ΧΑΝΙΑ", mediaid: 1802, logo: "/logos/gr/mini/superfm896.gif" }, 
{ mediatitle: "Super FM 89,6", city: "ΧΑΝΙΑ", mediaid: 1803, logo: "/logos/gr/mini/superfm896.gif" }, 
{ mediatitle: "SupeRadio 90,4", city: "ΗΡΑΚΛΕΙΟ", mediaid: 235, logo: "/logos/gr/mini/superadio904.gif" }, 
{ mediatitle: "Synora Fm 92,2", city: "ΚΙΛΚΙΣ", mediaid: 249, logo: "/logos/gr/mini/synorafm.gif" }, 
{ mediatitle: "Ta Elafakia ", city: "ΡΟΔΟΣ", mediaid: 1958, logo: "/logos/gr/mini/taelafakia.gif" }, 
{ mediatitle: "Team Fm 102", city: "ΡΕΘΥΜΝΟ", mediaid: 275, logo: "/logos/gr/mini/teamfm.gif" }, 
{ mediatitle: "The Pop Fm 98,6", city: "ΜΥΤΙΛΗΝΗ", mediaid: 399, logo: "/logos/gr/mini/thepopfm.gif" }, 
{ mediatitle: "Top Fm 96,9", city: "ΞΑΝΘΗ", mediaid: 379, logo: "/logos/gr/mini/topfmxanthi.gif" }, 
{ mediatitle: "Top Fm 106,4", city: "ΒΟΛΟΣ", mediaid: 523, logo: "/logos/gr/mini/topfmvolos.gif" }, 
{ mediatitle: "Top Fm ", city: "ΙΩΑΝΝΙΝΑ", mediaid: 473, logo: "/logos/gr/mini/topfmioannina.gif" }, 
{ mediatitle: "Top Fm 102,4", city: "ΡΟΔΟΣ", mediaid: 232, logo: "/logos/gr/mini/topfm.gif" }, 
{ mediatitle: "Top Melody 104,9", city: "ΣΑΝΤΟΡΙΝΗ", mediaid: 763, logo: "/logos/gr/mini/topmelody.gif" }, 
{ mediatitle: "Traffic FM 91,8", city: "ΗΡΑΚΛΕΙΟ", mediaid: 348, logo: "/logos/gr/mini/trafficfm.gif" }, 
{ mediatitle: "Trance Athens ", city: "INTERNET RADIO", mediaid: 1915, logo: "/logos/gr/mini/tranceathens.gif" }, 
{ mediatitle: "Trip Radio ", city: "INTERNET RADIO", mediaid: 728, logo: "/logos/gr/mini/tripradio.gif" }, 
{ mediatitle: "Trust Radio ", city: "INTERNET RADIO", mediaid: 1191, logo: "/logos/gr/mini/trustradiothess.gif" }, 
{ mediatitle: "Tuning Radio ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 889, logo: "/logos/gr/mini/tuningradio.gif" }, 
{ mediatitle: "Underground Radio 100,3", city: "ΞΑΝΘΗ", mediaid: 515, logo: "/logos/gr/mini/undergroundradio.gif" }, 
{ mediatitle: "UOC 96,7", city: "ΗΡΑΚΛΕΙΟ", mediaid: 233, logo: "/logos/gr/mini/uoc.gif" }, 
{ mediatitle: "UpLifted ", city: "INTERNET RADIO", mediaid: 769, logo: "/logos/gr/mini/uplifted.gif" }, 
{ mediatitle: "Urban Radio ", city: "INTERNET RADIO", mediaid: 1805, logo: "/logos/gr/mini/urbanradiogr.gif" }, 
{ mediatitle: "Velvet 96,8", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 540, logo: "/logos/gr/mini/velvet968.gif" }, 
{ mediatitle: "Velvet.Fm ", city: "ΑΘΗΝΑ", mediaid: 3, logo: "/logos/gr/mini/velvet.gif" }, 
{ mediatitle: "Venus 91,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1864, logo: "/logos/gr/mini/venusthess.gif" }, 
{ mediatitle: "Venus Fm 105,1", city: "ΑΜΑΛΙΑΔΑ", mediaid: 779, logo: "/logos/gr/mini/venusfm.gif" }, 
{ mediatitle: "Veto Fm 91", city: "ΚΟΖΑΝΗ", mediaid: 945, logo: "/logos/gr/mini/vetofm.gif" }, 
{ mediatitle: "VFM 88,3", city: "ΑΘΗΝΑ", mediaid: 292, logo: "/logos/gr/mini/VFM.gif" }, 
{ mediatitle: "ViaSound ", city: "INTERNET RADIO", mediaid: 1880, logo: "/logos/gr/mini/viasound.gif" }, 
{ mediatitle: "Virgin 104,5", city: "ΡΟΔΟΣ", mediaid: 1923, logo: "/logos/gr/mini/virgin1045.gif" }, 
{ mediatitle: "Viva 88,3", city: "ΚΑΤΕΡΙΝΗ", mediaid: 1871, logo: "/logos/gr/mini/viva883.gif" }, 
{ mediatitle: "Viva FM 95,3", city: "ΠΤΟΛEΜΑΙΔΑ", mediaid: 1136, logo: "/logos/gr/mini/vivafm953.gif" }, 
{ mediatitle: "Wasteland ", city: "INTERNET RADIO", mediaid: 862, logo: "/logos/gr/mini/wasteland.gif" }, 
{ mediatitle: "Wave Radio ", city: "INTERNET RADIO", mediaid: 797, logo: "/logos/gr/mini/waveradio.gif" }, 
{ mediatitle: "West Radio ", city: "INTERNET RADIO", mediaid: 1857, logo: "/logos/gr/mini/westradiogr.gif" }, 
{ mediatitle: "Xanthi DeeJay 90,6", city: "ΞΑΝΘΗ", mediaid: 452, logo: "/logos/gr/mini/xanthidj.gif" }, 
{ mediatitle: "X-Music Radio ", city: "INTERNET RADIO", mediaid: 925, logo: "/logos/gr/mini/xmusic.gif" }, 
{ mediatitle: "YES! 91,2", city: "ΠΑΤΡΑ", mediaid: 1834, logo: "/logos/gr/mini/yes912.gif" }, 
{ mediatitle: "You Fm 100,1", city: "ΠΑΤΡΑ", mediaid: 238, logo: "/logos/gr/mini/youfm.gif" }, 
{ mediatitle: "YouRadio 89", city: "ΗΡΑΚΛΕΙΟ", mediaid: 1807, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Zbutsam ", city: "INTERNET RADIO", mediaid: 1855, logo: "/logos/gr/mini/zbutsam.gif" }, 
{ mediatitle: "Zoo 90,8", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 97, logo: "/logos/gr/mini/zoo.gif" }, 
{ mediatitle: "Αγιος Σπυρίδων 91,1", city: "ΚΕΡΚΥΡΑ", mediaid: 689, logo: "/logos/gr/mini/spyridon.gif" }, 
{ mediatitle: "Αγρίνιο FM 93,7", city: "ΑΓΡΙΝΙΟ", mediaid: 312, logo: "/logos/gr/mini/agriniofm937.gif" }, 
{ mediatitle: "Αθήνα 984 98,3", city: "ΑΘΗΝΑ", mediaid: 107, logo: "/logos/gr/mini/athina984.gif" }, 
{ mediatitle: "Αιγαίο Live 95,8", city: "ΣΥΡΟΣ", mediaid: 972, logo: "/logos/gr/mini/aigaio958.gif" }, 
{ mediatitle: "Αίολος 92,8", city: "ΜΥΤΙΛΗΝΗ", mediaid: 1430, logo: "/logos/gr/mini/aeolos.gif" }, 
{ mediatitle: "ΑΚΜΗ Radio ", city: "ΑΘΗΝΑ", mediaid: 1891, logo: "/logos/gr/mini/iekakmi.gif" }, 
{ mediatitle: "Ακρόαμα 97,8", city: "ΚΑΒΑΛΑ", mediaid: 1823, logo: "/logos/gr/mini/akroama978.gif" }, 
{ mediatitle: "ΑλήΘεια Fm 96,3", city: "ΚΑΛΥΜΝΟΣ", mediaid: 1237, logo: "/logos/gr/mini/alithiafm.gif" }, 
{ mediatitle: "Αλφα 104", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 194, logo: "/logos/gr/mini/alfa.gif" }, 
{ mediatitle: "Ανατολικός Fm 95,8", city: "ΑΡΓΟΣ", mediaid: 664, logo: "/logos/gr/mini/anatolikos.gif" }, 
{ mediatitle: "Ανεμος 95,6", city: "ΣΑΜΟΣ", mediaid: 831, logo: "/logos/gr/mini/anemosfm.gif" }, 
{ mediatitle: "Αρης Fm 92,8", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 279, logo: "/logos/gr/mini/arisfm.gif" }, 
{ mediatitle: "Αρχάγγελος 94,1", city: "ΡΟΔΟΣ", mediaid: 217, logo: "/logos/gr/mini/arhagelos.gif" }, 
{ mediatitle: "Βημα Fm 99,5", city: "ΑΘΗΝΑ", mediaid: 722, logo: "/logos/gr/mini/vimafm995.gif" }, 
{ mediatitle: "Βήμα Fm 90,1", city: "ΙΩΑΝΝΙΝΑ", mediaid: 730, logo: "/logos/gr/mini/vimafm.gif" }, 
{ mediatitle: "Γαύδος Fm 88,8", city: "ΓΑYΔΟΣ", mediaid: 786, logo: "/logos/gr/mini/gavdosfm.gif" }, 
{ mediatitle: "Δημοτικό Ραδιόφωνο Πολύγυρου 90,8", city: "ΠΟΛΥΓΥΡΟΣ", mediaid: 867, logo: "/logos/gr/mini/poligiros.gif" }, 
{ mediatitle: "Δημοτικό Ραδιόφωνο Σκιάθου 96,4", city: "ΣΚΙΑΘΟΣ", mediaid: 1779, logo: "/logos/gr/mini/skiathos964.gif" }, 
{ mediatitle: "Δημοτικό Τρίπολης 91,5", city: "ΤΡΙΠΟΛΗ", mediaid: 544, logo: "/logos/gr/mini/drt.gif" }, 
{ mediatitle: "Διάστασις ", city: "INTERNET RADIO", mediaid: 1761, logo: "/logos/gr/mini/diastasis.gif" }, 
{ mediatitle: "Δίαυλος Δράμας 93", city: "ΔΡΑΜΑ", mediaid: 1112, logo: "/logos/gr/mini/diavlosdramas.gif" }, 
{ mediatitle: "Δίαυλος Καρδίτσας ", city: "ΚΑΡΔΙΤΣΑ", mediaid: 875, logo: "/logos/gr/mini/diavloskarditsas.gif" }, 
{ mediatitle: "Δίαυλος Ροδόπης 92,4", city: "ΚΟΜΟΤHΝΗ", mediaid: 174, logo: "/logos/gr/mini/diavlosrodopis.gif" }, 
{ mediatitle: "Δίεση 101,3", city: "ΑΘΗΝΑ", mediaid: 82, logo: "/logos/gr/mini/diesi.gif" }, 
{ mediatitle: "Δίκτυο 102,4", city: "ΣΕΡΡΕΣ", mediaid: 511, logo: "/logos/gr/mini/diktyo.gif" }, 
{ mediatitle: "Δίφωνο 96,6", city: "ΑΘΗΝΑ", mediaid: 1233, logo: "/logos/gr/mini/difono.gif" }, 
{ mediatitle: "Δρόμος 89,8", city: "ΑΘΗΝΑ", mediaid: 203, logo: "/logos/gr/mini/dromosfm.gif" }, 
{ mediatitle: "Εκκλησία της Ελλάδος 89,5", city: "ΑΘΗΝΑ", mediaid: 111, logo: "/logos/gr/mini/ecclesia.gif" }, 
{ mediatitle: "Εκπαιδευτήρια Κωστέα-Γείτονα ", city: "INTERNET RADIO", mediaid: 796, logo: "/logos/gr/mini/cgs.gif" }, 
{ mediatitle: "Εκρηξη Fm 99,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 458, logo: "/logos/gr/mini/radioekriksi.gif" }, 
{ mediatitle: "Ελεύθερη Ραδιοφωνία Κεφαλλονιά 93,9", city: "ΚΕΦΑΛΛΟΝΙΑ", mediaid: 872, logo: "/logos/gr/mini/erk.gif" }, 
{ mediatitle: "Ελλάδα Fm 96,7", city: "ΣΠΑΡΤΗ", mediaid: 712, logo: "/logos/gr/mini/elladaradio.gif" }, 
{ mediatitle: "Ελλάδα FM 98,7", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 295, logo: "/logos/gr/mini/elladafm.gif" }, 
{ mediatitle: "Ελληνάδικο FM ", city: "INTERNET RADIO", mediaid: 1866, logo: "/logos/gr/mini/ellinadikofm.gif" }, 
{ mediatitle: "Ελληνικό Παραδοσιακό ", city: "ΑΘΗΝΑ", mediaid: 533, logo: "/logos/gr/mini/elpar.gif" }, 
{ mediatitle: "Ελληνικός 88,9", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 658, logo: "/logos/gr/mini/ellinikos889.gif" }, 
{ mediatitle: "Ελληνορθόδοξη Παραδοση κ Ζωή 106", city: "ΧΑΛΚΙΔΙΚΗ", mediaid: 72, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Εν Λευκώ 87,7", city: "ΑΘΗΝΑ", mediaid: 88, logo: "/logos/gr/mini/enlefko.gif" }, 
{ mediatitle: "'Ενα Plus 98,5", city: "ΛΑΜΙΑ", mediaid: 45, logo: "/logos/gr/mini/enaplus985.gif" }, 
{ mediatitle: "Ενημέρωση 92,2", city: "ΚΑΤΕΡΙΝΗ", mediaid: 653, logo: "/logos/gr/mini/enimerosi.gif" }, 
{ mediatitle: "ΕΡΑ Δεύτερο 103,7", city: "ΑΘΗΝΑ", mediaid: 84, logo: "/logos/gr/mini/eradeutero.gif" }, 
{ mediatitle: "ΕΡΑ Κομοτηνής 98,4", city: "ΚΟΜΟΤHΝΗ", mediaid: 134, logo: "/logos/gr/mini/eraweb.gif" }, 
{ mediatitle: "ΕΡΑ Κόσμος 93,6", city: "ΑΘΗΝΑ", mediaid: 113, logo: "/logos/gr/mini/erakosmos.gif" }, 
{ mediatitle: "ΕΡΑ ΝΕΤ 105,8", city: "ΑΘΗΝΑ", mediaid: 105, logo: "/logos/gr/mini/eranet.gif" }, 
{ mediatitle: "ΕΡΑ Σπορ 101,8", city: "ΑΘΗΝΑ", mediaid: 109, logo: "/logos/gr/mini/erasport.gif" }, 
{ mediatitle: "ΕΡΑ Τρίτο 90,9", city: "ΑΘΗΝΑ", mediaid: 87, logo: "/logos/gr/mini/eratrito.gif" }, 
{ mediatitle: "ΕΡΑ Φιλία ", city: "ΑΘΗΝΑ", mediaid: 112, logo: "/logos/gr/mini/erafilia.gif" }, 
{ mediatitle: "ΕΡΑ Φωνή της Ελλάδας ", city: "ΑΘΗΝΑ", mediaid: 108, logo: "/logos/gr/mini/VOG.gif" }, 
{ mediatitle: "ΕΡΑ3 Α΄ Πρόγραμμα 102", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 118, logo: "/logos/gr/mini/102fm.gif" }, 
{ mediatitle: "ΕΡΑ3 Γ' Πρόγραμμα ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 120, logo: "/logos/gr/mini/trito.gif" }, 
{ mediatitle: "Ερμής 91,8", city: "ΖΑΚΥΝΘΟΣ", mediaid: 827, logo: "/logos/gr/mini/ermisradio.gif" }, 
{ mediatitle: "Ερωτικό 99,5", city: "ΚΟΖΑΝΗ", mediaid: 447, logo: "/logos/gr/mini/kardia.gif" }, 
{ mediatitle: "Ερωτικός 94,8", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 93, logo: "/logos/gr/mini/Erotikos.gif" }, 
{ mediatitle: "Ζιζάνιο 89,2", city: "ΑΡΓΟΣΤΟΛΙ", mediaid: 408, logo: "/logos/gr/mini/zizanio.gif" }, 
{ mediatitle: "Η Φωνή της Ελασσόνας ", city: "ΕΛΑΣΣOΝΑ", mediaid: 1808, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "ΗXΩ Fm 99,8", city: "ΛΑΣΙΘΙ", mediaid: 192, logo: "/logos/gr/mini/hxofm.gif" }, 
{ mediatitle: "Ηχόραμα Radio 100,8", city: "ΚΑΡΔΙΤΣΑ", mediaid: 524, logo: "/logos/gr/mini/ixorama.gif" }, 
{ mediatitle: "Ηχος 91", city: "ΛΑΡΙΣΑ", mediaid: 876, logo: "/logos/gr/mini/ixoslarisa.gif" }, 
{ mediatitle: "Ήχος Fm 94,2", city: "ΡΕΘΥΜΝΟ", mediaid: 469, logo: "/logos/gr/mini/ixosfm.gif" }, 
{ mediatitle: "Ήχος Radio ", city: "INTERNET RADIO", mediaid: 1900, logo: "/logos/gr/mini/hxosradio.gif" }, 
{ mediatitle: "Θράκη Fm 99,8", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 636, logo: "/logos/gr/mini/thrakifm.gif" }, 
{ mediatitle: "Ι.Μ. Αργολίδος 105,2", city: "ΝΑΥΠΛΙΟ", mediaid: 1770, logo: "/logos/gr/mini/imargol1052.gif" }, 
{ mediatitle: "Ι.Μ. Σύρου ", city: "ΣΥΡΟΣ", mediaid: 1249, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ι.Μ. Φθιώτιδας 89,4", city: "ΛΑΜΙΑ", mediaid: 1384, logo: "/logos/gr/mini/imf894.gif" }, 
{ mediatitle: "Ι.Μητρόπολις Πατρών 88,4", city: "ΠΑΤΡΑ", mediaid: 302, logo: "/logos/gr/mini/impatron.gif" }, 
{ mediatitle: "ΙΕΚ Δομή Radio ", city: "ΑΘΗΝΑ", mediaid: 944, logo: "/logos/gr/mini/iekdomi.gif" }, 
{ mediatitle: "Ιωάννινα Deejay 89,6", city: "ΙΩΑΝΝΙΝΑ", mediaid: 424, logo: "/logos/gr/mini/ioanninadj.gif" }, 
{ mediatitle: "Καλαμαριά FM 101,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 545, logo: "/logos/gr/mini/kalamariafm.gif" }, 
{ mediatitle: "Κανάλι 20 107,5", city: "ΚΑΛΑΜΑΤΑ", mediaid: 665, logo: "/logos/gr/mini/kanali20.gif" }, 
{ mediatitle: "Κανάλι 3 104", city: "ΦΛΩΡΙΝΑ", mediaid: 496, logo: "/logos/gr/mini/kanali3.gif" }, 
{ mediatitle: "Καραμέλα ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 598, logo: "/logos/gr/mini/mousikollima.gif" }, 
{ mediatitle: "Καστοριά Fm 91,5", city: "ΚΑΣΤΟΡΙΑ", mediaid: 195, logo: "/logos/gr/mini/kastoriafm.gif" }, 
{ mediatitle: "Κέντρο Καρδιάς 95", city: "ΗΡΑΚΛΕΙΟ", mediaid: 791, logo: "/logos/gr/mini/kentrokardias.gif" }, 
{ mediatitle: "ΚΛΙΚ FM 106,2", city: "ΡΟΔΟΣ", mediaid: 1762, logo: "/logos/gr/mini/klikfm1062.gif" }, 
{ mediatitle: "Κνωσσός Fm 100,6", city: "ΗΡΑΚΛΕΙΟ", mediaid: 488, logo: "/logos/gr/mini/knossosfm.gif" }, 
{ mediatitle: "Κοσμοράδιο 95,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 90, logo: "/logos/gr/mini/kosmoradio.gif" }, 
{ mediatitle: "Κόσμος 96,5", city: "ΑΡΓΟΣΤΟΛΙ", mediaid: 640, logo: "/logos/gr/mini/cosmos965.gif" }, 
{ mediatitle: "Κρήτη Fm 100,3", city: "ΗΡΑΚΛΕΙΟ", mediaid: 901, logo: "/logos/gr/mini/kriti1003.gif" }, 
{ mediatitle: "Κρητικός 88,7", city: "ΗΡΑΚΛΕΙΟ", mediaid: 47, logo: "/logos/gr/mini/kritikos.gif" }, 
{ mediatitle: "Κρητόραμα FM 97,9", city: "ΗΡΑΚΛΕΙΟ", mediaid: 1091, logo: "/logos/gr/mini/kritorama.gif" }, 
{ mediatitle: "Κύμα Fm 90,3", city: "ΚΕΡΚΥΡΑ", mediaid: 309, logo: "/logos/gr/mini/kymaradio.gif" }, 
{ mediatitle: "Λαϊκός 87,6", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 744, logo: "/logos/gr/mini/laikos.gif" }, 
{ mediatitle: "Λαϊκός FM 107,9", city: "INTERNET RADIO", mediaid: 1949, logo: "/logos/gr/mini/disco80s.gif" }, 
{ mediatitle: "ΛΑΚΚΑ ΣΟΥΛΙ Radio ", city: "INTERNET RADIO", mediaid: 869, logo: "/logos/gr/mini/lakkasouli.gif" }, 
{ mediatitle: "Λαμία FM 1 96,2", city: "ΛΑΜΙΑ", mediaid: 1218, logo: "/logos/gr/mini/lamiafm1.gif" }, 
{ mediatitle: "Λάμψη 92,3", city: "ΑΘΗΝΑ", mediaid: 293, logo: "/logos/gr/mini/lampsifm.gif" }, 
{ mediatitle: "Λατώ Fm 103,3", city: "ΑΓ.ΝΙΚΟΛΑΟΣ", mediaid: 376, logo: "/logos/gr/mini/latofm.gif" }, 
{ mediatitle: "Λέσχη 97,6", city: "ΤΡΙΚΑΛΑ", mediaid: 482, logo: "/logos/gr/mini/radioclub.gif" }, 
{ mediatitle: "Λευκάδα News ", city: "ΛΕΥΚΑΔΑ", mediaid: 1829, logo: "/logos/gr/mini/leukadanews.gif" }, 
{ mediatitle: "Λυδία FM 94,2", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 679, logo: "/logos/gr/mini/lydiafm.gif" }, 
{ mediatitle: "Μ.Ε.Α.Σ Ράδιο Λήμνος 98", city: "ΚΥΘΗΡΑ", mediaid: 1809, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Μάνα Ελλάδα ", city: "INTERNET RADIO", mediaid: 1826, logo: "/logos/gr/mini/manaellada.gif" }, 
{ mediatitle: "Μεθόριος 96", city: "ΟΡΕΣΤΙΑΔΑ", mediaid: 67, logo: "/logos/gr/mini/methorios.gif" }, 
{ mediatitle: "Μελωδία 99,2", city: "ΑΘΗΝΑ", mediaid: 83, logo: "/logos/gr/mini/melodia.gif" }, 
{ mediatitle: "Μελωδία 102,7", city: "ΡΕΘΥΜΝΟ", mediaid: 961, logo: "/logos/gr/mini/melodia1027.gif" }, 
{ mediatitle: "Μελωδία Fm 88", city: "ΛΑΜΙΑ", mediaid: 501, logo: "/logos/gr/mini/melodiafm.gif" }, 
{ mediatitle: "Μελωδίες Web Radio ", city: "ΑΘΗΝΑ", mediaid: 1963, logo: "/logos/gr/mini/melodiesweb.gif" }, 
{ mediatitle: "Μεσόγειος 105,4", city: "ΝΑΞΟΣ", mediaid: 911, logo: "/logos/gr/mini/mesogios.gif" }, 
{ mediatitle: "Μεσόγειος 95,7", city: "ΚΑΛΑΜΑΤΑ", mediaid: 1777, logo: "/logos/gr/mini/mesogeios957.gif" }, 
{ mediatitle: "Μήλος 108 108", city: "ΜΗΛΟΣ", mediaid: 1897, logo: "/logos/gr/mini/milos108.gif" }, 
{ mediatitle: "Μοναχική Διακονία 87,5", city: "ΒΟΛΟΣ", mediaid: 1031, logo: "/logos/gr/mini/monaxikidiakonia.gif" }, 
{ mediatitle: "Μουσικό Κανάλι 101,3", city: "ΡΕΘΥΜΝΟ", mediaid: 654, logo: "/logos/gr/mini/musikokanali.gif" }, 
{ mediatitle: "Μουσικό Κανάλι 105,1", city: "ΗΡΑΚΛΕΙΟ", mediaid: 687, logo: "/logos/gr/mini/mousikokanali.gif" }, 
{ mediatitle: "Μουσικό Κανάλι Ελασσόνας 107,3", city: "ΕΛΑΣΣOΝΑ", mediaid: 767, logo: "/logos/gr/mini/mousikoelas.gif" }, 
{ mediatitle: "Μουσικό Πανόραμα 100,8", city: "ΚΑΤΕΡΙΝΗ", mediaid: 1811, logo: "/logos/gr/mini/mouspan1008new.gif" }, 
{ mediatitle: "Μουσικό Πανόραμα Int'l Radio ", city: "ΚΑΤΕΡΙΝΗ", mediaid: 1952, logo: "/logos/gr/mini/mouspanintl.gif" }, 
{ mediatitle: "Μουσικός Παλμός 94,5", city: "ΝΕΑΠΟΛΗ", mediaid: 1760, logo: "/logos/gr/mini/mouspalmos945.gif" }, 
{ mediatitle: "Νέο Ραδιόφωνο 97,9", city: "ΚΕΡΚΥΡΑ", mediaid: 357, logo: "/logos/gr/mini/neoradiofono.gif" }, 
{ mediatitle: "Νικολάου Radio ", city: "ΑΘΗΝΑ", mediaid: 799, logo: "/logos/gr/mini/nikolaou.gif" }, 
{ mediatitle: "Νότος 94,9", city: "ΣΠΑΡΤΗ", mediaid: 953, logo: "/logos/gr/mini/notos949.gif" }, 
{ mediatitle: "Όγδοο ", city: "INTERNET RADIO", mediaid: 1905, logo: "/logos/gr/mini/ogdoo2.gif" }, 
{ mediatitle: "ΟΞΥΓΟΝΟ 106+6 106,6", city: "ΛΑΡΙΣΑ", mediaid: 1812, logo: "/logos/gr/mini/oxygono1066.gif" }, 
{ mediatitle: "Ορθοδοξία και Παράδοση 103", city: "ΣΙΑΤΙΣΤΑ", mediaid: 775, logo: "/logos/gr/mini/orthodoxia.gif" }, 
{ mediatitle: "Παλμός 105,4", city: "ΑΘΗΝΑ", mediaid: 657, logo: "/logos/gr/mini/palmosonair.gif" }, 
{ mediatitle: "Παλμός 95", city: "ΛΑΜΙΑ", mediaid: 1216, logo: "/logos/gr/mini/palmos95.gif" }, 
{ mediatitle: "Παλμός 90,5", city: "ΚΑΛΑΜΑΤΑ", mediaid: 652, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Παλμός 96,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 539, logo: "/logos/gr/mini/palmos965.gif" }, 
{ mediatitle: "Παλμός 99,5", city: "ΡΟΔΟΣ", mediaid: 1876, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Παλμός FM 94,9", city: "ΧΙΟΣ", mediaid: 1907, logo: "/logos/gr/mini/palmos949.gif" }, 
{ mediatitle: "Πανόραμα Fm 101,8", city: "ΠΤΟΛEΜΑΙΔΑ", mediaid: 497, logo: "/logos/gr/mini/panoramafm.gif" }, 
{ mediatitle: "Πάνος Γεραμάνης ", city: "INTERNET RADIO", mediaid: 912, logo: "/logos/gr/mini/geramanis.gif" }, 
{ mediatitle: "Πάρος Fm 98,5", city: "ΠΑΡΟΣ - ΑΝΤΙΠΑΡΟΣ", mediaid: 535, logo: "/logos/gr/mini/parosfm.gif" }, 
{ mediatitle: "Παύλειος Λόγος Ι.Μ. Βέροιας 90,2", city: "ΒΕΡΟΙΑ", mediaid: 1757, logo: "/logos/gr/mini/pavleioslogos.gif" }, 
{ mediatitle: "Πειραϊκή Εκκλησία 91,2", city: "ΑΘΗΝΑ", mediaid: 204, logo: "/logos/gr/mini/peiraios.gif" }, 
{ mediatitle: "Πέλλα FM 103,2", city: "ΓΙΑΝΝΙΤΣΑ", mediaid: 42, logo: "/logos/gr/mini/pellafm.gif" }, 
{ mediatitle: "Πολιτεία 90,7", city: "ΣΠΑΡΤΗ", mediaid: 633, logo: "/logos/gr/mini/politia.gif" }, 
{ mediatitle: "Πρίσμα 93,8", city: "ΞΥΛΟΚΑΣΤΡΟ", mediaid: 50, logo: "/logos/gr/mini/prismavirus.gif" }, 
{ mediatitle: "Πρωινός Fm 105,3", city: "ΤΡΙΚΑΛΑ", mediaid: 824, logo: "/logos/gr/mini/proinosfm.gif" }, 
{ mediatitle: "Ράδιο 1 102,5", city: "ΒΟΛΟΣ", mediaid: 1903, logo: "/logos/gr/mini/radio11025.gif" }, 
{ mediatitle: "Ράδιο Aλφα 96", city: "", mediaid: 993, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ράδιο Αλεξάνδρεια 97,7", city: "ΑΛΕΞΑΝΔΡΕΙΑ", mediaid: 938, logo: "/logos/gr/mini/alexandria.gif" }, 
{ mediatitle: "Ράδιο Αλέξανδρος 98,2", city: "ΝΕΑ ΠΕΡΑΜΟΣ", mediaid: 476, logo: "/logos/gr/mini/radioalexandros.gif" }, 
{ mediatitle: "Ράδιο Αμφισσα 104,4", city: "ΑΜΦΙΣΣΑ", mediaid: 651, logo: "/logos/gr/mini/radioamfissa.gif" }, 
{ mediatitle: "Ράδιο Α-Ω 90,4", city: "ΧΙΟΣ", mediaid: 980, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ράδιο Γάμμα 94", city: "ΠΑΤΡΑ", mediaid: 731, logo: "/logos/gr/mini/radiogamma.gif" }, 
{ mediatitle: "Ράδιο Γρεβενά 101,5", city: "ΓΡΕΒΕΝΑ", mediaid: 741, logo: "/logos/gr/mini/radiogrevena.gif" }, 
{ mediatitle: "Ράδιο ΔΕΘ 104,9", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 759, logo: "/logos/gr/mini/radiodeth.gif" }, 
{ mediatitle: "ΡΑΔΙΟ ΔΙΣΤΟΜΟ 106,1", city: "ΛΙΒΑΔΕΙΑ", mediaid: 1847, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ράδιο Δράμα 99,1", city: "ΔΡΑΜΑ", mediaid: 222, logo: "/logos/gr/mini/radiodrama.gif" }, 
{ mediatitle: "Ράδιο Έκφραση 92,4", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 220, logo: "/logos/gr/mini/ekfrasi.gif" }, 
{ mediatitle: "ΡΑΔΙΟ ΕΝΕΡΓΕΙΑ 106,4", city: "ΚΟΡΙΝΘΟΣ", mediaid: 1813, logo: "/logos/gr/mini/energeia1064.gif" }, 
{ mediatitle: "Ράδιο Εντεχνος ", city: "ΠΑΤΡΑ", mediaid: 960, logo: "/logos/gr/mini/entexnosfm.gif" }, 
{ mediatitle: "Ράδιο Επίδαυρος 93,8", city: "ΕΠΙΔΑΥΡΟΣ", mediaid: 456, logo: "/logos/gr/mini/radioepidavros.gif" }, 
{ mediatitle: "Ράδιο Επιλογές 102,8", city: "ΚΙΛΚΙΣ", mediaid: 865, logo: "/logos/gr/mini/epiloges.gif" }, 
{ mediatitle: "Ράδιο Ερμιονίδα 104,3", city: "ΚΡΑΝΙΔΙ", mediaid: 708, logo: "/logos/gr/mini/ermionidaradio.gif" }, 
{ mediatitle: "Ράδιο Ηπειρος 94,5", city: "ΙΩΑΝΝΙΝΑ", mediaid: 726, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ράδιο Θεσσαλονίκη 94,5", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 89, logo: "/logos/gr/mini/radiothess.gif" }, 
{ mediatitle: "Ράδιο Ιστιαία 100,4", city: "ΙΣΤΙΑΙΑ", mediaid: 1908, logo: "/logos/gr/mini/istiaea.gif" }, 
{ mediatitle: "Ράδιο Ιωνία 105,2", city: "ΣΑΜΟΣ", mediaid: 770, logo: "/logos/gr/mini/radioionia.gif" }, 
{ mediatitle: "Ράδιο Καλλονή 95,8", city: "ΚΑΛΛΟΝΗ", mediaid: 798, logo: "/logos/gr/mini/radiokalloni.gif" }, 
{ mediatitle: "Ράδιο Καρπενήσι 97,5", city: "ΚΑΡΠΕΝΗΣΙ", mediaid: 714, logo: "/logos/gr/mini/karpenisi.gif" }, 
{ mediatitle: "Ράδιο Καστελλόριζο 104,3", city: "", mediaid: 1752, logo: "/logos/gr/mini/kastellorizo.gif" }, 
{ mediatitle: "Ράδιο Κιβωτός 99,2", city: "ΣΕΡΡΕΣ", mediaid: 1199, logo: "/logos/gr/mini/kivotosserres.gif" }, 
{ mediatitle: "Ράδιο Κόσμος 100", city: "ΧΑΛΚΙΔΑ", mediaid: 313, logo: "/logos/gr/mini/kosmos100.gif" }, 
{ mediatitle: "Ράδιο Κρέστενα 101,3", city: "ΚΡΕΣΤΕΝΑ", mediaid: 684, logo: "/logos/gr/mini/krestena.gif" }, 
{ mediatitle: "Ράδιο Κρήτη 101,5", city: "ΗΡΑΚΛΕΙΟ", mediaid: 124, logo: "/logos/gr/mini/radiokriti.gif" }, 
{ mediatitle: "Ράδιο Κυπαρισσία 93,6", city: "ΚΥΠΑΡΙΣΣΙΑ", mediaid: 44, logo: "/logos/gr/mini/936.gif" }, 
{ mediatitle: "Ράδιο Λευκάδα 88,4", city: "ΛΕΥΚΑΔΑ", mediaid: 1873, logo: "/logos/gr/mini/lefkada884.gif" }, 
{ mediatitle: "Ράδιο Λευκίμμη 105,5", city: "ΚΕΡΚΥΡΑ", mediaid: 1075, logo: "/logos/gr/mini/lefkimmi.gif" }, 
{ mediatitle: "Ράδιο Λέχοβο 97,1", city: "ΦΛΩΡΙΝΑ", mediaid: 647, logo: "/logos/gr/mini/radiolehovo.gif" }, 
{ mediatitle: "Ράδιο Μακιστία 98,6", city: "ΠΥΡΓΟΣ", mediaid: 955, logo: "/logos/gr/mini/makistia.gif" }, 
{ mediatitle: "Ράδιο Μεγαλόνησος 89,8", city: "ΡΕΘΥΜΝΟ", mediaid: 1875, logo: "/logos/gr/mini/megalonisos898.gif" }, 
{ mediatitle: "Ράδιο Μέλι 106", city: "ΚΟΖΑΝΗ", mediaid: 1872, logo: "/logos/gr/mini/meli106.gif" }, 
{ mediatitle: "Ράδιο Μοίρες ", city: "ΗΡΑΚΛΕΙΟ", mediaid: 644, logo: "/logos/gr/mini/radiomires.gif" }, 
{ mediatitle: "Ράδιο Νίκη 96,4", city: "ΦΙΛΙΑΤΡΑ", mediaid: 756, logo: "/logos/gr/mini/radioniki.gif" }, 
{ mediatitle: "Ράδιο Παρατηρητής 94", city: "ΚΟΜΟΤHΝΗ", mediaid: 1845, logo: "/logos/gr/mini/paratiritis.gif" }, 
{ mediatitle: "Ράδιο Πατρίδα 100,4", city: "ΚΟΜΟΤHΝΗ", mediaid: 1783, logo: "/logos/gr/mini/radiopatrida1004.gif" }, 
{ mediatitle: "Ράδιο Πιερία 104,2", city: "ΚΑΤΕΡΙΝΗ", mediaid: 843, logo: "/logos/gr/mini/radiopieria.gif" }, 
{ mediatitle: "Ράδιο Πόλις 99,4", city: "ΛΑΡΙΣΑ", mediaid: 54, logo: "/logos/gr/mini/radiopolis.gif" }, 
{ mediatitle: "Ράδιο Πρέβεζα 93", city: "ΠΡΕΒΕΖΑ", mediaid: 226, logo: "/logos/gr/mini/radiopreveza.gif" }, 
{ mediatitle: "Ράδιο Πρωϊνή 93,7", city: "ΚΑΒΑΛΑ", mediaid: 1066, logo: "/logos/gr/mini/proini937.gif" }, 
{ mediatitle: "Ράδιο Ροδόπη 95,5", city: "ΚΟΜΟΤHΝΗ", mediaid: 1069, logo: "/logos/gr/mini/radiorodopi.gif" }, 
{ mediatitle: "Ράδιο Ρωμαίος 94", city: "ΙΩΑΝΝΙΝΑ", mediaid: 1713, logo: "/logos/gr/mini/romeos.gif" }, 
{ mediatitle: "Ράδιο Σάμος 102", city: "ΣΑΜΟΣ", mediaid: 830, logo: "/logos/gr/mini/radiosamos.gif" }, 
{ mediatitle: "Ράδιο Σαντορίνης 106,4", city: "ΣΑΝΤΟΡΙΝΗ", mediaid: 747, logo: "/logos/gr/mini/santorini1.gif" }, 
{ mediatitle: "Ράδιο Σιάτιστας ", city: "ΣΙΑΤΙΣΤΑ", mediaid: 826, logo: "/logos/gr/mini/radiosiatistas.gif" }, 
{ mediatitle: "Ράδιο Συχνότητα 100,7", city: "ΑΙΓΙΟ", mediaid: 1849, logo: "/logos/gr/mini/syxnotita102.gif" }, 
{ mediatitle: "Ράδιο Τύπος 99,7", city: "ΒΕΡΟΙΑ", mediaid: 55, logo: "/logos/gr/mini/typosfm.gif" }, 
{ mediatitle: "Ράδιο Υπάρχω 103,7", city: "ΡΕΘΥΜΝΟ", mediaid: 902, logo: "/logos/gr/mini/nologo.gif" }, 
{ mediatitle: "Ράδιο Φάρος 92,7", city: "ΙΩΑΝΝΙΝΑ", mediaid: 777, logo: "/logos/gr/mini/faros927.gif" }, 
{ mediatitle: "Ράδιο Φάση ", city: "INTERNET RADIO", mediaid: 781, logo: "/logos/gr/mini/radiofasi.gif" }, 
{ mediatitle: "Ράδιο Φάση ", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 1890, logo: "/logos/gr/mini/radiofasi.gif" }, 
{ mediatitle: "Ράδιο Φλώρινα 101,5", city: "ΦΛΩΡΙΝΑ", mediaid: 745, logo: "/logos/gr/mini/radioflorina.gif" }, 
{ mediatitle: "Ράδιο Ωροπός ", city: "INTERNET RADIO", mediaid: 1889, logo: "/logos/gr/mini/oropos.gif" }, 
{ mediatitle: "Ραδιοκύματα 104", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 746, logo: "/logos/gr/mini/radiokimata.gif" }, 
{ mediatitle: "Ραδιοκύματα 102,6", city: "ΡΕΘΥΜΝΟ", mediaid: 547, logo: "/logos/gr/mini/radiokimatare.gif" }, 
{ mediatitle: "Ραδιοφωνία Αγιάς 94,2", city: "ΛΑΡΙΣΑ", mediaid: 510, logo: "/logos/gr/mini/ayia942.gif" }, 
{ mediatitle: "Ραδιοφωνία Κισσάβου 97,8", city: "ΛΑΡΙΣΑ", mediaid: 11, logo: "/logos/gr/mini/kissavos.gif" }, 
{ mediatitle: "Ραδιοφωνία Τριφυλίας 101,3", city: "ΚΥΠΑΡΙΣΣΙΑ", mediaid: 906, logo: "/logos/gr/mini/trifylias.gif" }, 
{ mediatitle: "Ραδιόφωνο 108", city: "ΜΥΤΙΛΗΝΗ", mediaid: 659, logo: "/logos/gr/mini/radiofono108.gif" }, 
{ mediatitle: "Ραδιόφωνο Άνω Βριλησσίων ", city: "ΑΘΗΝΑ", mediaid: 1831, logo: "/logos/gr/mini/avrilissia.gif" }, 
{ mediatitle: "Ραδιόφωνο ΑΠΕ - ΜΠΕ ", city: "INTERNET RADIO", mediaid: 77, logo: "/logos/gr/mini/anampa.gif" }, 
{ mediatitle: "Ραδιόφωνο Λυχνάρι 91,7", city: "ΡΟΔΟΣ", mediaid: 196, logo: "/logos/gr/mini/lihnari.gif" }, 
{ mediatitle: "Ραδιόφωνο Μεσολογγίου 92", city: "ΜΕΣΟΛΟΓΓΙ", mediaid: 739, logo: "/logos/gr/mini/mesologgi.gif" }, 
{ mediatitle: "Ρόδον Fm 95", city: "ΣΕΡΡΕΣ", mediaid: 838, logo: "/logos/gr/mini/rodonfm.gif" }, 
{ mediatitle: "Ρυθμός 104,4", city: "ΚΟΖΑΝΗ", mediaid: 800, logo: "/logos/gr/mini/rythmos1044.gif" }, 
{ mediatitle: "Ρυθμός 94,6", city: "ΛΑΜΙΑ", mediaid: 1215, logo: "/logos/gr/mini/rythmos946.gif" }, 
{ mediatitle: "Ρυθμός 104,5", city: "ΗΡΑΚΛΕΙΟ", mediaid: 190, logo: "/logos/gr/mini/rythmoscrete.gif" }, 
{ mediatitle: "Ρυθμός 94,9", city: "ΑΘΗΝΑ", mediaid: 215, logo: "/logos/gr/mini/rythmos.gif" }, 
{ mediatitle: "Ρυθμός 98,8", city: "ΛΑΡΙΣΑ", mediaid: 404, logo: "/logos/gr/mini/rythmos988.gif" }, 
{ mediatitle: "Ρυθμός 94,3", city: "ΖΑΚΥΝΘΟΣ", mediaid: 454, logo: "/logos/gr/mini/rythmos943.gif" }, 
{ mediatitle: "Ρυθμός 106", city: "ΞΑΝΘΗ", mediaid: 451, logo: "/logos/gr/mini/rythmosxan.gif" }, 
{ mediatitle: "Ρυθμός Fm 103,8", city: "ΑΡΓΟΣ", mediaid: 290, logo: "/logos/gr/mini/rythmos1038.gif" }, 
{ mediatitle: "Σαγαπώ 96,1", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 514, logo: "/logos/gr/mini/sagapo.gif" }, 
{ mediatitle: "Σάμος Fm 97,3", city: "ΣΑΜΟΣ", mediaid: 358, logo: "/logos/gr/mini/samosfm.gif" }, 
{ mediatitle: "Σεβντάς FM ", city: "INTERNET RADIO", mediaid: 1932, logo: "/logos/gr/mini/sevdasgr.gif" }, 
{ mediatitle: "Σείριος FM ", city: "ΛΙΒΑΔΕΙΑ", mediaid: 923, logo: "/logos/gr/mini/siriosfm.gif" }, 
{ mediatitle: "Σκάϊ Radio 100,3", city: "ΑΘΗΝΑ", mediaid: 103, logo: "/logos/gr/mini/skai.gif" }, 
{ mediatitle: "Σοχός Fm 88,7", city: "ΘΕΣΣΑΛΟΝΙΚΗ", mediaid: 842, logo: "/logos/gr/mini/sohos.gif" }, 
{ mediatitle: "Σταθμός ", city: "INTERNET RADIO", mediaid: 81, logo: "/logos/gr/mini/stathmos.gif" }, 
{ mediatitle: "Στίγμα Radio 97,6", city: "ΖΑΚΥΝΘΟΣ", mediaid: 178, logo: "/logos/gr/mini/StigmaFm.gif" }, 
{ mediatitle: "Στόχος Fm 98,9", city: "ΘΑΣΟΣ", mediaid: 733, logo: "/logos/gr/mini/stoxosfm.gif" }, 
{ mediatitle: "Σφήνα Radio ", city: "INTERNET RADIO", mediaid: 1931, logo: "/logos/gr/mini/sfinagr.gif" }, 
{ mediatitle: "Σφηνάκια FM 97,3", city: "", mediaid: 1714, logo: "/logos/gr/mini/sfinakiafm.gif" }, 
{ mediatitle: "Τάλως FM 88,6", city: "ΡΕΘΥΜΝΟ", mediaid: 1710, logo: "/logos/gr/mini/talosfm886.gif" }, 
{ mediatitle: "Τοξότης 96,3", city: "ΓΙΑΝΝΙΤΣΑ", mediaid: 635, logo: "/logos/gr/mini/toxotisfm.gif" }, 
{ mediatitle: "Υδρόγειος 106,9", city: "ΗΡΑΚΛΕΙΟ", mediaid: 181, logo: "/logos/gr/mini/ydrogeios.gif" }, 
{ mediatitle: "Υπάρχω 101,4", city: "ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ", mediaid: 874, logo: "/logos/gr/mini/yparxo.gif" }, 
{ mediatitle: "Φάρος Fm 104", city: "ΣΥΡΟΣ", mediaid: 35, logo: "/logos/gr/mini/farosfm.gif" }, 
{ mediatitle: "Φάσμα 103", city: "ΠΤΟΛEΜΑΙΔΑ", mediaid: 505, logo: "/logos/gr/mini/fasmafm.gif" }, 
{ mediatitle: "Χιακή Φωνή 90", city: "ΧΙΟΣ", mediaid: 360, logo: "/logos/gr/mini/xiaki.gif" }, 
{ mediatitle: "Χριστιανισμός ", city: "ΑΘΗΝΑ", mediaid: 219, logo: "/logos/gr/mini/christianity.gif" }, 
{ mediatitle: "Χρόνος 87,5", city: "ΚΟΜΟΤHΝΗ", mediaid: 888, logo: "/logos/gr/mini/xronosfm.gif" }, 
{ mediatitle: "Χρώματα Έρωτος ", city: "INTERNET RADIO", mediaid: 950, logo: "/logos/gr/mini/ixoxromma.gif" }
];
